-- FastERP PostgreSQL baseline and SAP Business One migration control plane.
--
-- Apply with a migration runner inside a transaction, or directly with:
--   psql "$DB_URL" -v ON_ERROR_STOP=1 -1 -f migrations/postgres/0001_fast_erp_baseline.sql
--
-- This migration is intentionally schema-qualified. It does not alter objects
-- outside the fast_erp schema and stores no SAP or database credentials.

CREATE SCHEMA IF NOT EXISTS fast_erp;

CREATE TABLE IF NOT EXISTS fast_erp.schema_migrations (
    version        TEXT PRIMARY KEY,
    applied_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- -------------------------------------------------------------------------
-- Organisation and shared reference data
-- -------------------------------------------------------------------------

CREATE TABLE fast_erp.currencies (
    code           CHAR(3) PRIMARY KEY,
    name           TEXT NOT NULL,
    symbol         TEXT NOT NULL,
    active         BOOLEAN NOT NULL DEFAULT true,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO fast_erp.currencies (code, name, symbol)
VALUES
    ('EUR', 'Euro', '€'),
    ('GBP', 'Pound sterling', '£'),
    ('USD', 'US dollar', '$')
ON CONFLICT (code) DO NOTHING;

CREATE TABLE fast_erp.companies (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code               TEXT NOT NULL UNIQUE,
    name               TEXT NOT NULL,
    country_code       CHAR(2) NOT NULL,
    local_currency     CHAR(3) NOT NULL REFERENCES fast_erp.currencies(code),
    timezone           TEXT NOT NULL DEFAULT 'UTC',
    fiscal_year_start  SMALLINT NOT NULL DEFAULT 1
                       CHECK (fiscal_year_start BETWEEN 1 AND 12),
    active             BOOLEAN NOT NULL DEFAULT true,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE fast_erp.exchange_rates (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id         BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    rate_date          DATE NOT NULL,
    from_currency      CHAR(3) NOT NULL REFERENCES fast_erp.currencies(code),
    to_currency        CHAR(3) NOT NULL REFERENCES fast_erp.currencies(code),
    rate               NUMERIC(20, 10) NOT NULL CHECK (rate > 0),
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (company_id, rate_date, from_currency, to_currency),
    CHECK (from_currency <> to_currency)
);

CREATE TABLE fast_erp.business_units (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id     BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    code           TEXT NOT NULL,
    name           TEXT NOT NULL,
    region         TEXT,
    active         BOOLEAN NOT NULL DEFAULT true,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (company_id, code)
);

CREATE TABLE fast_erp.plants (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id     BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    code           TEXT NOT NULL,
    name           TEXT NOT NULL,
    country_code   CHAR(2),
    active         BOOLEAN NOT NULL DEFAULT true,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (company_id, code)
);

CREATE TABLE fast_erp.warehouses (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id     BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    plant_id       BIGINT REFERENCES fast_erp.plants(id),
    code           TEXT NOT NULL,
    name           TEXT NOT NULL,
    active         BOOLEAN NOT NULL DEFAULT true,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (company_id, code)
);

CREATE TABLE fast_erp.accounts (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id         BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    code               TEXT NOT NULL,
    name               TEXT NOT NULL,
    account_type       TEXT NOT NULL,
    normal_side        TEXT NOT NULL CHECK (normal_side IN ('Debit', 'Credit')),
    parent_account_id  BIGINT REFERENCES fast_erp.accounts(id),
    active             BOOLEAN NOT NULL DEFAULT true,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (company_id, code),
    UNIQUE (company_id, name)
);

CREATE TABLE fast_erp.tax_codes (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id     BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    code           TEXT NOT NULL,
    name           TEXT NOT NULL,
    rate           NUMERIC(9, 6) NOT NULL CHECK (rate >= 0),
    recoverable    BOOLEAN NOT NULL DEFAULT false,
    active         BOOLEAN NOT NULL DEFAULT true,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (company_id, code)
);

-- -------------------------------------------------------------------------
-- Business partners, products, inventory, and projects
-- -------------------------------------------------------------------------

CREATE TABLE fast_erp.customers (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id     BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    code           TEXT,
    name           TEXT NOT NULL,
    territory      TEXT,
    credit_limit   NUMERIC(20, 4),
    currency       CHAR(3) REFERENCES fast_erp.currencies(code),
    active         BOOLEAN NOT NULL DEFAULT true,
    created        DATE,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (company_id, code)
);

CREATE TABLE fast_erp.suppliers (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id     BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    code           TEXT,
    name           TEXT NOT NULL,
    territory      TEXT,
    currency       CHAR(3) REFERENCES fast_erp.currencies(code),
    active         BOOLEAN NOT NULL DEFAULT true,
    created        DATE,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (company_id, code)
);

CREATE TABLE fast_erp.business_partner_addresses (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id    BIGINT REFERENCES fast_erp.customers(id) ON DELETE CASCADE,
    supplier_id    BIGINT REFERENCES fast_erp.suppliers(id) ON DELETE CASCADE,
    address_type   TEXT NOT NULL CHECK (address_type IN ('Billing', 'Shipping', 'Other')),
    label          TEXT,
    address_1      TEXT,
    address_2      TEXT,
    city           TEXT,
    state_region   TEXT,
    postal_code    TEXT,
    country_code   CHAR(2),
    is_default     BOOLEAN NOT NULL DEFAULT false,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK ((customer_id IS NOT NULL) <> (supplier_id IS NOT NULL))
);

CREATE TABLE fast_erp.items (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id         BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    code               TEXT NOT NULL,
    name               TEXT NOT NULL,
    item_group         TEXT,
    uom                TEXT,
    rate               NUMERIC(20, 4),
    stock_qty          NUMERIC(20, 6) NOT NULL DEFAULT 0,
    reorder_level      NUMERIC(20, 6) NOT NULL DEFAULT 0,
    inventory_item     BOOLEAN NOT NULL DEFAULT true,
    active             BOOLEAN NOT NULL DEFAULT true,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (company_id, code)
);

CREATE TABLE fast_erp.item_warehouse_stock (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id            BIGINT NOT NULL REFERENCES fast_erp.items(id) ON DELETE CASCADE,
    warehouse_id       BIGINT NOT NULL REFERENCES fast_erp.warehouses(id),
    quantity           NUMERIC(20, 6) NOT NULL DEFAULT 0,
    committed_qty      NUMERIC(20, 6) NOT NULL DEFAULT 0,
    ordered_qty        NUMERIC(20, 6) NOT NULL DEFAULT 0,
    average_cost       NUMERIC(20, 6),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (item_id, warehouse_id)
);

CREATE TABLE fast_erp.projects (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id         BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    code               TEXT NOT NULL,
    name               TEXT NOT NULL,
    customer_id        BIGINT REFERENCES fast_erp.customers(id),
    business_unit_id   BIGINT REFERENCES fast_erp.business_units(id),
    status             TEXT NOT NULL,
    budget             NUMERIC(20, 4) NOT NULL DEFAULT 0,
    start_date         DATE,
    end_date           DATE,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (company_id, code),
    CHECK (end_date IS NULL OR start_date IS NULL OR end_date >= start_date)
);

-- -------------------------------------------------------------------------
-- Selling and receivables
-- -------------------------------------------------------------------------

CREATE TABLE fast_erp.sales_orders (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id         BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    code               TEXT NOT NULL,
    customer_id        BIGINT REFERENCES fast_erp.customers(id),
    order_date         DATE,
    delivery_date      DATE,
    status             TEXT NOT NULL DEFAULT 'Draft'
                       CHECK (status IN ('Draft', 'Confirmed', 'Delivered', 'Invoiced',
                                         'Closed', 'Cancelled')),
    currency           CHAR(3) NOT NULL REFERENCES fast_erp.currencies(code),
    exchange_rate      NUMERIC(20, 10) NOT NULL DEFAULT 1 CHECK (exchange_rate > 0),
    total              NUMERIC(20, 4) NOT NULL DEFAULT 0 CHECK (total >= 0),
    note               TEXT,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (company_id, code)
);

CREATE TABLE fast_erp.sales_order_items (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id       BIGINT NOT NULL REFERENCES fast_erp.sales_orders(id) ON DELETE CASCADE,
    line_number    INTEGER NOT NULL,
    item_id        BIGINT REFERENCES fast_erp.items(id),
    warehouse_id   BIGINT REFERENCES fast_erp.warehouses(id),
    description    TEXT,
    qty            NUMERIC(20, 6) NOT NULL CHECK (qty >= 0),
    rate           NUMERIC(20, 4) NOT NULL CHECK (rate >= 0),
    amount         NUMERIC(20, 4) NOT NULL CHECK (amount >= 0),
    tax_code_id    BIGINT REFERENCES fast_erp.tax_codes(id),
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (order_id, line_number)
);

CREATE TABLE fast_erp.invoices (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id         BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    code               TEXT NOT NULL,
    order_id           BIGINT REFERENCES fast_erp.sales_orders(id),
    customer_id        BIGINT REFERENCES fast_erp.customers(id),
    invoice_date       DATE,
    due_date           DATE,
    currency           CHAR(3) NOT NULL REFERENCES fast_erp.currencies(code),
    exchange_rate      NUMERIC(20, 10) NOT NULL DEFAULT 1 CHECK (exchange_rate > 0),
    net_total          NUMERIC(20, 4) NOT NULL DEFAULT 0 CHECK (net_total >= 0),
    tax_total          NUMERIC(20, 4) NOT NULL DEFAULT 0 CHECK (tax_total >= 0),
    total              NUMERIC(20, 4) NOT NULL DEFAULT 0 CHECK (total >= 0),
    paid               NUMERIC(20, 4) NOT NULL DEFAULT 0 CHECK (paid >= 0),
    status             TEXT NOT NULL DEFAULT 'Unpaid'
                       CHECK (status IN ('Unpaid', 'Partly Paid', 'Paid', 'Overdue',
                                         'Cancelled')),
    note               TEXT,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (company_id, code),
    CHECK (due_date IS NULL OR invoice_date IS NULL OR due_date >= invoice_date)
);

CREATE TABLE fast_erp.invoice_items (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id     BIGINT NOT NULL REFERENCES fast_erp.invoices(id) ON DELETE CASCADE,
    line_number    INTEGER NOT NULL,
    item_id        BIGINT REFERENCES fast_erp.items(id),
    warehouse_id   BIGINT REFERENCES fast_erp.warehouses(id),
    description    TEXT,
    qty            NUMERIC(20, 6) NOT NULL CHECK (qty >= 0),
    rate           NUMERIC(20, 4) NOT NULL CHECK (rate >= 0),
    net_amount     NUMERIC(20, 4) NOT NULL DEFAULT 0 CHECK (net_amount >= 0),
    tax_amount     NUMERIC(20, 4) NOT NULL DEFAULT 0 CHECK (tax_amount >= 0),
    amount         NUMERIC(20, 4) NOT NULL DEFAULT 0 CHECK (amount >= 0),
    tax_code_id    BIGINT REFERENCES fast_erp.tax_codes(id),
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (invoice_id, line_number)
);

CREATE TABLE fast_erp.payments (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id         BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    code               TEXT NOT NULL,
    customer_id        BIGINT REFERENCES fast_erp.customers(id),
    payment_date       DATE NOT NULL,
    currency           CHAR(3) NOT NULL REFERENCES fast_erp.currencies(code),
    exchange_rate      NUMERIC(20, 10) NOT NULL DEFAULT 1 CHECK (exchange_rate > 0),
    amount             NUMERIC(20, 4) NOT NULL CHECK (amount > 0),
    status             TEXT NOT NULL DEFAULT 'Posted'
                       CHECK (status IN ('Draft', 'Posted', 'Cancelled')),
    note               TEXT,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (company_id, code)
);

CREATE TABLE fast_erp.payment_allocations (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id     BIGINT NOT NULL REFERENCES fast_erp.payments(id) ON DELETE CASCADE,
    invoice_id     BIGINT NOT NULL REFERENCES fast_erp.invoices(id),
    amount         NUMERIC(20, 4) NOT NULL CHECK (amount > 0),
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (payment_id, invoice_id)
);

-- -------------------------------------------------------------------------
-- Purchasing and stock
-- -------------------------------------------------------------------------

CREATE TABLE fast_erp.purchase_orders (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id         BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    code               TEXT NOT NULL,
    supplier_id        BIGINT REFERENCES fast_erp.suppliers(id),
    order_date         DATE,
    status             TEXT NOT NULL DEFAULT 'Draft'
                       CHECK (status IN ('Draft', 'Ordered', 'Received', 'Cancelled')),
    currency           CHAR(3) NOT NULL REFERENCES fast_erp.currencies(code),
    exchange_rate      NUMERIC(20, 10) NOT NULL DEFAULT 1 CHECK (exchange_rate > 0),
    total              NUMERIC(20, 4) NOT NULL DEFAULT 0 CHECK (total >= 0),
    note               TEXT,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (company_id, code)
);

CREATE TABLE fast_erp.purchase_order_items (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    po_id          BIGINT NOT NULL REFERENCES fast_erp.purchase_orders(id) ON DELETE CASCADE,
    line_number    INTEGER NOT NULL,
    item_id        BIGINT REFERENCES fast_erp.items(id),
    warehouse_id   BIGINT REFERENCES fast_erp.warehouses(id),
    description    TEXT,
    qty            NUMERIC(20, 6) NOT NULL CHECK (qty >= 0),
    rate           NUMERIC(20, 4) NOT NULL CHECK (rate >= 0),
    amount         NUMERIC(20, 4) NOT NULL CHECK (amount >= 0),
    tax_code_id    BIGINT REFERENCES fast_erp.tax_codes(id),
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (po_id, line_number)
);

CREATE TABLE fast_erp.stock_moves (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id         BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    item_id            BIGINT NOT NULL REFERENCES fast_erp.items(id),
    warehouse_id       BIGINT REFERENCES fast_erp.warehouses(id),
    move_date          DATE NOT NULL,
    direction          TEXT NOT NULL CHECK (direction IN ('In', 'Out')),
    qty                NUMERIC(20, 6) NOT NULL CHECK (qty > 0),
    unit_cost          NUMERIC(20, 6),
    ref                TEXT,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- -------------------------------------------------------------------------
-- Accounting and supporting records
-- -------------------------------------------------------------------------

CREATE TABLE fast_erp.expenses (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id         BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    code               TEXT NOT NULL,
    expense_date       DATE NOT NULL,
    supplier_id        BIGINT REFERENCES fast_erp.suppliers(id),
    category           TEXT NOT NULL,
    description        TEXT,
    net_amount         NUMERIC(20, 4) NOT NULL CHECK (net_amount >= 0),
    tax_amount         NUMERIC(20, 4) NOT NULL DEFAULT 0 CHECK (tax_amount >= 0),
    total              NUMERIC(20, 4) NOT NULL CHECK (total >= 0),
    currency           CHAR(3) NOT NULL REFERENCES fast_erp.currencies(code),
    exchange_rate      NUMERIC(20, 10) NOT NULL DEFAULT 1 CHECK (exchange_rate > 0),
    business_unit_id   BIGINT REFERENCES fast_erp.business_units(id),
    project_id         BIGINT REFERENCES fast_erp.projects(id),
    status             TEXT NOT NULL DEFAULT 'Posted'
                       CHECK (status IN ('Draft', 'Posted', 'Cancelled')),
    note               TEXT,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (company_id, code)
);

CREATE TABLE fast_erp.journal_entries (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id     BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    code           TEXT NOT NULL,
    entry_date     DATE NOT NULL,
    memo           TEXT,
    status         TEXT NOT NULL DEFAULT 'Posted'
                   CHECK (status IN ('Draft', 'Posted', 'Cancelled')),
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (company_id, code)
);

CREATE TABLE fast_erp.journal_lines (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    journal_id         BIGINT NOT NULL REFERENCES fast_erp.journal_entries(id)
                       ON DELETE CASCADE,
    line_number        INTEGER NOT NULL,
    account_id         BIGINT NOT NULL REFERENCES fast_erp.accounts(id),
    debit              NUMERIC(20, 4) NOT NULL DEFAULT 0 CHECK (debit >= 0),
    credit             NUMERIC(20, 4) NOT NULL DEFAULT 0 CHECK (credit >= 0),
    currency           CHAR(3) REFERENCES fast_erp.currencies(code),
    foreign_amount     NUMERIC(20, 4),
    business_unit_id   BIGINT REFERENCES fast_erp.business_units(id),
    project_id         BIGINT REFERENCES fast_erp.projects(id),
    memo               TEXT,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (journal_id, line_number),
    CHECK ((debit > 0 AND credit = 0) OR (credit > 0 AND debit = 0))
);

CREATE TABLE fast_erp.gl_entries (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id         BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    entry_date         DATE NOT NULL,
    account_id         BIGINT NOT NULL REFERENCES fast_erp.accounts(id),
    debit              NUMERIC(20, 4) NOT NULL DEFAULT 0 CHECK (debit >= 0),
    credit             NUMERIC(20, 4) NOT NULL DEFAULT 0 CHECK (credit >= 0),
    ref                TEXT,
    business_unit_id   BIGINT REFERENCES fast_erp.business_units(id),
    project_id         BIGINT REFERENCES fast_erp.projects(id),
    currency           CHAR(3) REFERENCES fast_erp.currencies(code),
    exchange_rate      NUMERIC(20, 10) NOT NULL DEFAULT 1 CHECK (exchange_rate > 0),
    memo               TEXT,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK ((debit > 0 AND credit = 0) OR (credit > 0 AND debit = 0))
);

CREATE TABLE fast_erp.transaction_links (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id     BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    source_ref     TEXT NOT NULL,
    target_ref     TEXT NOT NULL,
    link_type      TEXT NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE fast_erp.attachments (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id     BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    entity_type    TEXT NOT NULL,
    entity_id      BIGINT NOT NULL,
    filename       TEXT NOT NULL,
    path           TEXT NOT NULL,
    content_hash   TEXT,
    note           TEXT,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE fast_erp.custom_fields (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id     BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    entity_type    TEXT NOT NULL,
    entity_id      BIGINT NOT NULL,
    field_name     TEXT NOT NULL,
    field_value    JSONB,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (company_id, entity_type, entity_id, field_name)
);

CREATE TABLE fast_erp.chat_messages (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thread_id      TEXT NOT NULL,
    role           TEXT NOT NULL,
    content        TEXT NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- -------------------------------------------------------------------------
-- SAP Business One migration control plane
-- -------------------------------------------------------------------------

CREATE TABLE fast_erp.migration_sources (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id             BIGINT REFERENCES fast_erp.companies(id),
    name                   TEXT NOT NULL UNIQUE,
    connector_type         TEXT NOT NULL
                           CHECK (connector_type IN (
                               'sap_business_one_odata_v4',
                               'sap_s4_odata',
                               'sap_ecc',
                               'csv_bundle',
                               'mock_sap'
                           )),
    base_url               TEXT,
    source_company_db      TEXT,
    credential_env_prefix TEXT,
    configuration          JSONB NOT NULL DEFAULT '{}'::jsonb,
    active                 BOOLEAN NOT NULL DEFAULT true,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON COLUMN fast_erp.migration_sources.configuration IS
    'Non-secret connector options only. Credentials are resolved from environment variables.';

CREATE TABLE fast_erp.migration_mapping_sets (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           TEXT NOT NULL,
    version        INTEGER NOT NULL DEFAULT 1 CHECK (version > 0),
    source_type    TEXT NOT NULL,
    status         TEXT NOT NULL DEFAULT 'Draft'
                   CHECK (status IN ('Draft', 'Approved', 'Retired')),
    description    TEXT,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    approved_at    TIMESTAMPTZ,
    UNIQUE (name, version)
);

CREATE TABLE fast_erp.migration_mapping_rules (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mapping_set_id     BIGINT NOT NULL REFERENCES fast_erp.migration_mapping_sets(id)
                       ON DELETE CASCADE,
    source_object      TEXT NOT NULL,
    source_field       TEXT NOT NULL,
    target_table       TEXT NOT NULL,
    target_field       TEXT NOT NULL,
    transform_type     TEXT NOT NULL DEFAULT 'copy'
                       CHECK (transform_type IN (
                           'copy', 'constant', 'lookup', 'expression', 'ignore'
                       )),
    transform_config   JSONB NOT NULL DEFAULT '{}'::jsonb,
    required           BOOLEAN NOT NULL DEFAULT false,
    ordinal            INTEGER NOT NULL DEFAULT 0,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (mapping_set_id, source_object, source_field, target_table, target_field)
);

CREATE TABLE fast_erp.migration_runs (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id          BIGINT NOT NULL REFERENCES fast_erp.migration_sources(id),
    mapping_set_id     BIGINT REFERENCES fast_erp.migration_mapping_sets(id),
    mode               TEXT NOT NULL DEFAULT 'cutover'
                       CHECK (mode IN ('discovery', 'dry_run', 'cutover')),
    status             TEXT NOT NULL DEFAULT 'Created'
                       CHECK (status IN (
                           'Created', 'Extracting', 'Staged', 'Validating', 'Validated',
                           'Approved', 'Applying', 'Reconciling', 'Completed', 'Failed',
                           'Cancelled'
                       )),
    history_from       DATE NOT NULL,
    history_to         DATE NOT NULL,
    scope              JSONB NOT NULL DEFAULT '{}'::jsonb,
    requested_by       TEXT,
    approved_by        TEXT,
    approved_at        TIMESTAMPTZ,
    started_at         TIMESTAMPTZ,
    completed_at       TIMESTAMPTZ,
    source_count       BIGINT NOT NULL DEFAULT 0,
    staged_count       BIGINT NOT NULL DEFAULT 0,
    applied_count      BIGINT NOT NULL DEFAULT 0,
    warning_count      BIGINT NOT NULL DEFAULT 0,
    error_count        BIGINT NOT NULL DEFAULT 0,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (history_to >= history_from),
    CHECK ((status <> 'Approved' AND approved_at IS NULL) OR approved_by IS NOT NULL)
);

CREATE TABLE fast_erp.migration_batches (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id             BIGINT NOT NULL REFERENCES fast_erp.migration_runs(id)
                       ON DELETE CASCADE,
    source_object      TEXT NOT NULL,
    sequence_number    INTEGER NOT NULL CHECK (sequence_number >= 0),
    status             TEXT NOT NULL DEFAULT 'Pending'
                       CHECK (status IN ('Pending', 'Extracted', 'Validated', 'Applied', 'Failed')),
    request_cursor     TEXT,
    response_cursor    TEXT,
    source_count       INTEGER NOT NULL DEFAULT 0,
    staged_count       INTEGER NOT NULL DEFAULT 0,
    applied_count      INTEGER NOT NULL DEFAULT 0,
    payload_hash       TEXT,
    started_at         TIMESTAMPTZ,
    completed_at       TIMESTAMPTZ,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (run_id, source_object, sequence_number)
);

CREATE TABLE fast_erp.migration_staging_records (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id             BIGINT NOT NULL REFERENCES fast_erp.migration_runs(id)
                       ON DELETE CASCADE,
    batch_id           BIGINT REFERENCES fast_erp.migration_batches(id)
                       ON DELETE CASCADE,
    source_object      TEXT NOT NULL,
    source_key         TEXT NOT NULL,
    source_document_no TEXT,
    source_updated_at  TIMESTAMPTZ,
    raw_payload        JSONB NOT NULL,
    normalized_payload JSONB,
    payload_hash       TEXT NOT NULL,
    status             TEXT NOT NULL DEFAULT 'Extracted'
                       CHECK (status IN (
                           'Extracted', 'Mapped', 'Valid', 'Warning', 'Invalid',
                           'Applied', 'Skipped', 'Failed'
                       )),
    target_table       TEXT,
    target_id          BIGINT,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (run_id, source_object, source_key)
);

CREATE TABLE fast_erp.migration_validation_issues (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id             BIGINT NOT NULL REFERENCES fast_erp.migration_runs(id)
                       ON DELETE CASCADE,
    staging_record_id  BIGINT REFERENCES fast_erp.migration_staging_records(id)
                       ON DELETE CASCADE,
    severity           TEXT NOT NULL CHECK (severity IN ('Info', 'Warning', 'Error')),
    rule_code          TEXT NOT NULL,
    field_name         TEXT,
    message            TEXT NOT NULL,
    details            JSONB NOT NULL DEFAULT '{}'::jsonb,
    resolved           BOOLEAN NOT NULL DEFAULT false,
    resolution_note    TEXT,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    resolved_at        TIMESTAMPTZ
);

CREATE TABLE fast_erp.migration_crosswalks (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id          BIGINT NOT NULL REFERENCES fast_erp.migration_sources(id),
    source_object      TEXT NOT NULL,
    source_key         TEXT NOT NULL,
    source_document_no TEXT,
    target_table       TEXT NOT NULL,
    target_id          BIGINT NOT NULL,
    payload_hash       TEXT NOT NULL,
    first_run_id       BIGINT NOT NULL REFERENCES fast_erp.migration_runs(id),
    last_run_id        BIGINT NOT NULL REFERENCES fast_erp.migration_runs(id),
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (source_id, source_object, source_key),
    UNIQUE (source_id, target_table, target_id)
);

CREATE TABLE fast_erp.external_references (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id          BIGINT NOT NULL REFERENCES fast_erp.migration_sources(id),
    entity_type        TEXT NOT NULL,
    entity_id          BIGINT NOT NULL,
    source_object      TEXT NOT NULL,
    source_key         TEXT NOT NULL,
    source_document_no TEXT,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (source_id, source_object, source_key),
    UNIQUE (source_id, entity_type, entity_id)
);

CREATE TABLE fast_erp.migration_checkpoints (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id         BIGINT NOT NULL REFERENCES fast_erp.migration_runs(id)
                   ON DELETE CASCADE,
    source_object  TEXT NOT NULL,
    cursor_value   TEXT,
    last_source_key TEXT,
    completed      BOOLEAN NOT NULL DEFAULT false,
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (run_id, source_object)
);

CREATE TABLE fast_erp.migration_reconciliations (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id         BIGINT NOT NULL REFERENCES fast_erp.migration_runs(id)
                   ON DELETE CASCADE,
    check_code     TEXT NOT NULL,
    object_type    TEXT,
    dimension      JSONB NOT NULL DEFAULT '{}'::jsonb,
    source_value   NUMERIC(30, 8),
    target_value   NUMERIC(30, 8),
    difference     NUMERIC(30, 8),
    passed         BOOLEAN NOT NULL,
    details        JSONB NOT NULL DEFAULT '{}'::jsonb,
    checked_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (run_id, check_code, object_type, dimension)
);

CREATE TABLE fast_erp.migration_audit_events (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id         BIGINT REFERENCES fast_erp.migration_runs(id) ON DELETE CASCADE,
    actor          TEXT,
    event_type     TEXT NOT NULL,
    message        TEXT NOT NULL,
    details        JSONB NOT NULL DEFAULT '{}'::jsonb,
    occurred_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- -------------------------------------------------------------------------
-- Operational and migration indexes
-- -------------------------------------------------------------------------

CREATE INDEX idx_customers_company_name
    ON fast_erp.customers (company_id, name);
CREATE INDEX idx_suppliers_company_name
    ON fast_erp.suppliers (company_id, name);
CREATE INDEX idx_items_company_group
    ON fast_erp.items (company_id, item_group);
CREATE INDEX idx_sales_orders_company_status
    ON fast_erp.sales_orders (company_id, status, order_date);
CREATE INDEX idx_invoices_company_status
    ON fast_erp.invoices (company_id, status, invoice_date);
CREATE INDEX idx_purchase_orders_company_status
    ON fast_erp.purchase_orders (company_id, status, order_date);
CREATE INDEX idx_stock_moves_item_date
    ON fast_erp.stock_moves (item_id, move_date);
CREATE INDEX idx_gl_entries_company_account_date
    ON fast_erp.gl_entries (company_id, account_id, entry_date);
CREATE INDEX idx_attachments_entity
    ON fast_erp.attachments (company_id, entity_type, entity_id);
CREATE INDEX idx_custom_fields_entity
    ON fast_erp.custom_fields (company_id, entity_type, entity_id);
CREATE INDEX idx_migration_runs_source_status
    ON fast_erp.migration_runs (source_id, status, created_at);
CREATE INDEX idx_migration_staging_status
    ON fast_erp.migration_staging_records (run_id, source_object, status);
CREATE INDEX idx_migration_staging_payload_gin
    ON fast_erp.migration_staging_records USING GIN (normalized_payload);
CREATE INDEX idx_migration_issues_open
    ON fast_erp.migration_validation_issues (run_id, severity)
    WHERE resolved = false;
CREATE INDEX idx_external_references_target
    ON fast_erp.external_references (entity_type, entity_id);
CREATE INDEX idx_migration_audit_run_time
    ON fast_erp.migration_audit_events (run_id, occurred_at);

INSERT INTO fast_erp.schema_migrations (version)
VALUES ('0001_fast_erp_baseline')
ON CONFLICT (version) DO NOTHING;
