-- Common document controls, fiscal periods, approvals, and audit history.

ALTER TABLE fast_erp.schema_migrations
    ADD COLUMN IF NOT EXISTS checksum TEXT;

CREATE TABLE fast_erp.document_sequences (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    document_type   TEXT NOT NULL,
    prefix          TEXT NOT NULL,
    next_number     BIGINT NOT NULL DEFAULT 1 CHECK (next_number > 0),
    padding         SMALLINT NOT NULL DEFAULT 6 CHECK (padding BETWEEN 1 AND 18),
    active          BOOLEAN NOT NULL DEFAULT true,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (company_id, document_type)
);

CREATE TABLE fast_erp.fiscal_periods (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    code            TEXT NOT NULL,
    starts_on       DATE NOT NULL,
    ends_on         DATE NOT NULL,
    status          TEXT NOT NULL DEFAULT 'Open'
                    CHECK (status IN ('Open', 'Soft Closed', 'Locked')),
    locked_at       TIMESTAMPTZ,
    locked_by       TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (company_id, code),
    CHECK (ends_on >= starts_on),
    CHECK ((status = 'Locked') = (locked_at IS NOT NULL))
);

CREATE TABLE fast_erp.roles (
    code            TEXT PRIMARY KEY,
    name            TEXT NOT NULL UNIQUE,
    description     TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO fast_erp.roles (code, name, description)
VALUES
    ('preparer', 'Preparer', 'Creates and edits draft documents'),
    ('approver', 'Approver', 'Approves documents and migration warnings'),
    ('administrator', 'Administrator', 'Posts, cancels, locks periods, and administers migrations')
ON CONFLICT (code) DO NOTHING;

CREATE TABLE fast_erp.company_user_roles (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    user_identifier TEXT NOT NULL,
    role_code       TEXT NOT NULL REFERENCES fast_erp.roles(code),
    active          BOOLEAN NOT NULL DEFAULT true,
    granted_by      TEXT,
    granted_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (company_id, user_identifier, role_code)
);

CREATE TABLE fast_erp.document_approvals (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    entity_type     TEXT NOT NULL,
    entity_id       BIGINT NOT NULL,
    action          TEXT NOT NULL CHECK (action IN ('Submitted', 'Approved', 'Rejected', 'Recalled')),
    actor           TEXT NOT NULL,
    note            TEXT,
    occurred_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE fast_erp.document_audit_events (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    entity_type     TEXT NOT NULL,
    entity_id       BIGINT NOT NULL,
    event_type      TEXT NOT NULL,
    actor           TEXT,
    previous_state  TEXT,
    next_state      TEXT,
    revision        INTEGER NOT NULL DEFAULT 1 CHECK (revision > 0),
    details         JSONB NOT NULL DEFAULT '{}'::jsonb,
    occurred_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE fast_erp.sales_orders
    ADD COLUMN IF NOT EXISTS document_state TEXT NOT NULL DEFAULT 'Draft',
    ADD COLUMN IF NOT EXISTS revision INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS row_version BIGINT NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS submitted_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS submitted_by TEXT,
    ADD COLUMN IF NOT EXISTS approved_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS approved_by TEXT,
    ADD COLUMN IF NOT EXISTS posted_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS posted_by TEXT,
    ADD COLUMN IF NOT EXISTS cancelled_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS cancelled_by TEXT,
    ADD COLUMN IF NOT EXISTS amended_from_id BIGINT REFERENCES fast_erp.sales_orders(id),
    ADD COLUMN IF NOT EXISTS reversal_of_id BIGINT REFERENCES fast_erp.sales_orders(id);

ALTER TABLE fast_erp.invoices
    ADD COLUMN IF NOT EXISTS document_state TEXT NOT NULL DEFAULT 'Draft',
    ADD COLUMN IF NOT EXISTS revision INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS row_version BIGINT NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS submitted_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS submitted_by TEXT,
    ADD COLUMN IF NOT EXISTS approved_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS approved_by TEXT,
    ADD COLUMN IF NOT EXISTS posted_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS posted_by TEXT,
    ADD COLUMN IF NOT EXISTS cancelled_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS cancelled_by TEXT,
    ADD COLUMN IF NOT EXISTS amended_from_id BIGINT REFERENCES fast_erp.invoices(id),
    ADD COLUMN IF NOT EXISTS reversal_of_id BIGINT REFERENCES fast_erp.invoices(id);

ALTER TABLE fast_erp.purchase_orders
    ADD COLUMN IF NOT EXISTS document_state TEXT NOT NULL DEFAULT 'Draft',
    ADD COLUMN IF NOT EXISTS revision INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS row_version BIGINT NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS submitted_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS submitted_by TEXT,
    ADD COLUMN IF NOT EXISTS approved_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS approved_by TEXT,
    ADD COLUMN IF NOT EXISTS posted_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS posted_by TEXT,
    ADD COLUMN IF NOT EXISTS cancelled_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS cancelled_by TEXT,
    ADD COLUMN IF NOT EXISTS amended_from_id BIGINT REFERENCES fast_erp.purchase_orders(id),
    ADD COLUMN IF NOT EXISTS reversal_of_id BIGINT REFERENCES fast_erp.purchase_orders(id);

ALTER TABLE fast_erp.payments
    ADD COLUMN IF NOT EXISTS document_state TEXT NOT NULL DEFAULT 'Draft',
    ADD COLUMN IF NOT EXISTS revision INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS row_version BIGINT NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS approved_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS approved_by TEXT,
    ADD COLUMN IF NOT EXISTS posted_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS posted_by TEXT,
    ADD COLUMN IF NOT EXISTS cancelled_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS cancelled_by TEXT,
    ADD COLUMN IF NOT EXISTS reversal_of_id BIGINT REFERENCES fast_erp.payments(id);

ALTER TABLE fast_erp.expenses
    ADD COLUMN IF NOT EXISTS document_state TEXT NOT NULL DEFAULT 'Draft',
    ADD COLUMN IF NOT EXISTS revision INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS row_version BIGINT NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS posted_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS posted_by TEXT,
    ADD COLUMN IF NOT EXISTS cancelled_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS cancelled_by TEXT,
    ADD COLUMN IF NOT EXISTS reversal_of_id BIGINT REFERENCES fast_erp.expenses(id);

ALTER TABLE fast_erp.journal_entries
    ADD COLUMN IF NOT EXISTS document_state TEXT NOT NULL DEFAULT 'Draft',
    ADD COLUMN IF NOT EXISTS revision INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS row_version BIGINT NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS posted_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS posted_by TEXT,
    ADD COLUMN IF NOT EXISTS cancelled_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS cancelled_by TEXT,
    ADD COLUMN IF NOT EXISTS reversal_of_id BIGINT REFERENCES fast_erp.journal_entries(id);

-- Deterministically classify rows created by the baseline/demo model. The old
-- status columns remain operational/derived status, while document_state owns
-- the posting lifecycle from this migration onward.
UPDATE fast_erp.sales_orders
   SET document_state = CASE status
       WHEN 'Draft' THEN 'Draft'
       WHEN 'Cancelled' THEN 'Cancelled'
       WHEN 'Closed' THEN 'Closed'
       ELSE 'Posted' END,
       posted_at = CASE WHEN status NOT IN ('Draft', 'Cancelled') THEN updated_at END,
       cancelled_at = CASE WHEN status = 'Cancelled' THEN updated_at END;

UPDATE fast_erp.invoices
   SET document_state = CASE status
       WHEN 'Cancelled' THEN 'Cancelled'
       ELSE 'Posted' END,
       posted_at = CASE WHEN status <> 'Cancelled' THEN updated_at END,
       cancelled_at = CASE WHEN status = 'Cancelled' THEN updated_at END;

UPDATE fast_erp.purchase_orders
   SET document_state = CASE status
       WHEN 'Draft' THEN 'Draft'
       WHEN 'Cancelled' THEN 'Cancelled'
       ELSE 'Posted' END,
       posted_at = CASE WHEN status NOT IN ('Draft', 'Cancelled') THEN updated_at END,
       cancelled_at = CASE WHEN status = 'Cancelled' THEN updated_at END;

UPDATE fast_erp.payments
   SET document_state = status,
       posted_at = CASE WHEN status = 'Posted' THEN updated_at END,
       cancelled_at = CASE WHEN status = 'Cancelled' THEN updated_at END;

UPDATE fast_erp.expenses
   SET document_state = status,
       posted_at = CASE WHEN status = 'Posted' THEN updated_at END,
       cancelled_at = CASE WHEN status = 'Cancelled' THEN updated_at END;

UPDATE fast_erp.journal_entries
   SET document_state = status,
       posted_at = CASE WHEN status = 'Posted' THEN updated_at END,
       cancelled_at = CASE WHEN status = 'Cancelled' THEN updated_at END;

ALTER TABLE fast_erp.sales_orders
    ADD CONSTRAINT sales_orders_document_state_check
    CHECK (document_state IN ('Draft', 'Pending Approval', 'Approved', 'Posted', 'Held', 'Closed', 'Cancelled'));
ALTER TABLE fast_erp.invoices
    ADD CONSTRAINT invoices_document_state_check
    CHECK (document_state IN ('Draft', 'Pending Approval', 'Approved', 'Posted', 'Held', 'Closed', 'Cancelled'));
ALTER TABLE fast_erp.purchase_orders
    ADD CONSTRAINT purchase_orders_document_state_check
    CHECK (document_state IN ('Draft', 'Pending Approval', 'Approved', 'Posted', 'Held', 'Closed', 'Cancelled'));
ALTER TABLE fast_erp.payments
    ADD CONSTRAINT payments_document_state_check
    CHECK (document_state IN ('Draft', 'Pending Approval', 'Approved', 'Posted', 'Held', 'Closed', 'Cancelled'));
ALTER TABLE fast_erp.expenses
    ADD CONSTRAINT expenses_document_state_check
    CHECK (document_state IN ('Draft', 'Pending Approval', 'Approved', 'Posted', 'Held', 'Closed', 'Cancelled'));
ALTER TABLE fast_erp.journal_entries
    ADD CONSTRAINT journal_entries_document_state_check
    CHECK (document_state IN ('Draft', 'Pending Approval', 'Approved', 'Posted', 'Held', 'Closed', 'Cancelled'));

CREATE INDEX idx_fiscal_periods_company_dates
    ON fast_erp.fiscal_periods (company_id, starts_on, ends_on);
CREATE INDEX idx_document_audit_entity
    ON fast_erp.document_audit_events (company_id, entity_type, entity_id, occurred_at);
CREATE INDEX idx_document_approvals_entity
    ON fast_erp.document_approvals (company_id, entity_type, entity_id, occurred_at);

INSERT INTO fast_erp.schema_migrations (version)
VALUES ('0002_document_controls')
ON CONFLICT (version) DO NOTHING;
