-- Unified business partners, UOMs, prices, payment terms, and tax rules.

CREATE TABLE fast_erp.business_partners (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    code            TEXT NOT NULL,
    name            TEXT NOT NULL,
    default_currency CHAR(3) REFERENCES fast_erp.currencies(code),
    tax_identifier  TEXT,
    credit_limit    NUMERIC(20, 4),
    payment_blocked BOOLEAN NOT NULL DEFAULT false,
    active          BOOLEAN NOT NULL DEFAULT true,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (company_id, code)
);

CREATE TABLE fast_erp.business_partner_roles (
    partner_id      BIGINT NOT NULL REFERENCES fast_erp.business_partners(id) ON DELETE CASCADE,
    role            TEXT NOT NULL CHECK (role IN ('Customer', 'Supplier')),
    receivable_account_id BIGINT REFERENCES fast_erp.accounts(id),
    payable_account_id BIGINT REFERENCES fast_erp.accounts(id),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (partner_id, role)
);

CREATE TABLE fast_erp.partner_addresses (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partner_id      BIGINT NOT NULL REFERENCES fast_erp.business_partners(id) ON DELETE CASCADE,
    address_type    TEXT NOT NULL CHECK (address_type IN ('Billing', 'Shipping', 'Remit To', 'Other')),
    label           TEXT,
    address_1       TEXT,
    address_2       TEXT,
    city            TEXT,
    state_region    TEXT,
    postal_code     TEXT,
    country_code    CHAR(2),
    is_default      BOOLEAN NOT NULL DEFAULT false,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE fast_erp.customers ADD COLUMN IF NOT EXISTS partner_id BIGINT REFERENCES fast_erp.business_partners(id);
ALTER TABLE fast_erp.suppliers ADD COLUMN IF NOT EXISTS partner_id BIGINT REFERENCES fast_erp.business_partners(id);
CREATE UNIQUE INDEX idx_customers_partner ON fast_erp.customers (partner_id) WHERE partner_id IS NOT NULL;
CREATE UNIQUE INDEX idx_suppliers_partner ON fast_erp.suppliers (partner_id) WHERE partner_id IS NOT NULL;

CREATE TABLE fast_erp.uoms (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            TEXT NOT NULL UNIQUE,
    name            TEXT NOT NULL,
    allows_fraction BOOLEAN NOT NULL DEFAULT true,
    active          BOOLEAN NOT NULL DEFAULT true,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO fast_erp.business_partners (
    company_id, code, name, default_currency, credit_limit, active, created_at, updated_at
)
SELECT company_id, COALESCE(code, 'CUSTOMER-' || id::text), name, currency,
       credit_limit, active, created_at, updated_at
  FROM fast_erp.customers
ON CONFLICT (company_id, code) DO NOTHING;

UPDATE fast_erp.customers customer
   SET partner_id = partner.id
  FROM fast_erp.business_partners partner
 WHERE partner.company_id = customer.company_id
   AND partner.code = COALESCE(customer.code, 'CUSTOMER-' || customer.id::text)
   AND customer.partner_id IS NULL;

INSERT INTO fast_erp.business_partner_roles (partner_id, role)
SELECT partner_id, 'Customer'
  FROM fast_erp.customers
 WHERE partner_id IS NOT NULL
ON CONFLICT (partner_id, role) DO NOTHING;

INSERT INTO fast_erp.business_partners (
    company_id, code, name, default_currency, active, created_at, updated_at
)
SELECT company_id, COALESCE(code, 'SUPPLIER-' || id::text), name, currency,
       active, created_at, updated_at
  FROM fast_erp.suppliers
ON CONFLICT (company_id, code) DO NOTHING;

UPDATE fast_erp.suppliers supplier
   SET partner_id = partner.id
  FROM fast_erp.business_partners partner
 WHERE partner.company_id = supplier.company_id
   AND partner.code = COALESCE(supplier.code, 'SUPPLIER-' || supplier.id::text)
   AND supplier.partner_id IS NULL;

INSERT INTO fast_erp.business_partner_roles (partner_id, role)
SELECT partner_id, 'Supplier'
  FROM fast_erp.suppliers
 WHERE partner_id IS NOT NULL
ON CONFLICT (partner_id, role) DO NOTHING;

INSERT INTO fast_erp.partner_addresses (
    partner_id, address_type, label, address_1, address_2, city, state_region,
    postal_code, country_code, is_default, created_at, updated_at
)
SELECT COALESCE(customer.partner_id, supplier.partner_id), legacy.address_type,
       legacy.label, legacy.address_1, legacy.address_2, legacy.city,
       legacy.state_region, legacy.postal_code, legacy.country_code,
       legacy.is_default, legacy.created_at, legacy.updated_at
  FROM fast_erp.business_partner_addresses legacy
  LEFT JOIN fast_erp.customers customer ON customer.id = legacy.customer_id
  LEFT JOIN fast_erp.suppliers supplier ON supplier.id = legacy.supplier_id
 WHERE COALESCE(customer.partner_id, supplier.partner_id) IS NOT NULL;

INSERT INTO fast_erp.uoms (code, name)
SELECT DISTINCT upper(trim(uom)), trim(uom)
  FROM fast_erp.items
 WHERE NULLIF(trim(uom), '') IS NOT NULL
ON CONFLICT (code) DO NOTHING;

CREATE TABLE fast_erp.item_uom_conversions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id         BIGINT NOT NULL REFERENCES fast_erp.items(id) ON DELETE CASCADE,
    from_uom_id     BIGINT NOT NULL REFERENCES fast_erp.uoms(id),
    to_uom_id       BIGINT NOT NULL REFERENCES fast_erp.uoms(id),
    factor          NUMERIC(20, 10) NOT NULL CHECK (factor > 0),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (item_id, from_uom_id, to_uom_id),
    CHECK (from_uom_id <> to_uom_id)
);

ALTER TABLE fast_erp.items
    ADD COLUMN IF NOT EXISTS stock_uom_id BIGINT REFERENCES fast_erp.uoms(id),
    ADD COLUMN IF NOT EXISTS valuation_method TEXT NOT NULL DEFAULT 'Moving Average',
    ADD COLUMN IF NOT EXISTS standard_cost NUMERIC(20, 6),
    ADD COLUMN IF NOT EXISTS tracks_serials BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS tracks_batches BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS tracks_expiry BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS allow_negative_stock BOOLEAN NOT NULL DEFAULT false;

UPDATE fast_erp.items item
   SET stock_uom_id = uom.id
  FROM fast_erp.uoms uom
 WHERE uom.code = upper(trim(item.uom))
   AND item.stock_uom_id IS NULL;

ALTER TABLE fast_erp.items
    ADD CONSTRAINT items_valuation_method_check
    CHECK (valuation_method IN ('Moving Average', 'FIFO', 'Standard Cost')),
    ADD CONSTRAINT items_tracking_check
    CHECK (NOT tracks_expiry OR tracks_batches);

CREATE TABLE fast_erp.price_books (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    code            TEXT NOT NULL,
    name            TEXT NOT NULL,
    purpose         TEXT NOT NULL CHECK (purpose IN ('Sales', 'Purchasing')),
    currency        CHAR(3) NOT NULL REFERENCES fast_erp.currencies(code),
    active          BOOLEAN NOT NULL DEFAULT true,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (company_id, code)
);

CREATE TABLE fast_erp.price_book_entries (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    price_book_id   BIGINT NOT NULL REFERENCES fast_erp.price_books(id) ON DELETE CASCADE,
    item_id         BIGINT NOT NULL REFERENCES fast_erp.items(id),
    uom_id          BIGINT REFERENCES fast_erp.uoms(id),
    minimum_qty     NUMERIC(20, 6) NOT NULL DEFAULT 0 CHECK (minimum_qty >= 0),
    unit_price      NUMERIC(20, 6) NOT NULL CHECK (unit_price >= 0),
    valid_from      DATE,
    valid_to        DATE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (valid_to IS NULL OR valid_from IS NULL OR valid_to >= valid_from)
);

CREATE TABLE fast_erp.payment_terms (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    code            TEXT NOT NULL,
    name            TEXT NOT NULL,
    due_days        INTEGER NOT NULL DEFAULT 0 CHECK (due_days >= 0),
    discount_days   INTEGER CHECK (discount_days >= 0),
    discount_percent NUMERIC(9, 6) CHECK (discount_percent BETWEEN 0 AND 100),
    active          BOOLEAN NOT NULL DEFAULT true,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (company_id, code)
);

CREATE TABLE fast_erp.bank_accounts (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    code            TEXT NOT NULL,
    name            TEXT NOT NULL,
    currency        CHAR(3) NOT NULL REFERENCES fast_erp.currencies(code),
    gl_account_id   BIGINT NOT NULL REFERENCES fast_erp.accounts(id),
    iban_masked     TEXT,
    active          BOOLEAN NOT NULL DEFAULT true,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (company_id, code)
);

ALTER TABLE fast_erp.tax_codes
    ADD COLUMN IF NOT EXISTS sales_account_id BIGINT REFERENCES fast_erp.accounts(id),
    ADD COLUMN IF NOT EXISTS purchase_account_id BIGINT REFERENCES fast_erp.accounts(id),
    ADD COLUMN IF NOT EXISTS country_code CHAR(2),
    ADD COLUMN IF NOT EXISTS valid_from DATE,
    ADD COLUMN IF NOT EXISTS valid_to DATE;

CREATE TABLE fast_erp.tax_rules (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    name            TEXT NOT NULL,
    priority        INTEGER NOT NULL DEFAULT 100,
    partner_role    TEXT CHECK (partner_role IN ('Customer', 'Supplier')),
    country_code    CHAR(2),
    item_group      TEXT,
    tax_code_id     BIGINT NOT NULL REFERENCES fast_erp.tax_codes(id),
    valid_from      DATE,
    valid_to        DATE,
    active          BOOLEAN NOT NULL DEFAULT true,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (valid_to IS NULL OR valid_from IS NULL OR valid_to >= valid_from)
);

CREATE INDEX idx_business_partners_company_name ON fast_erp.business_partners (company_id, name);
CREATE INDEX idx_price_book_entries_lookup ON fast_erp.price_book_entries (price_book_id, item_id, minimum_qty);
CREATE INDEX idx_tax_rules_lookup ON fast_erp.tax_rules (company_id, active, priority);

INSERT INTO fast_erp.schema_migrations (version)
VALUES ('0003_commercial_masters')
ON CONFLICT (version) DO NOTHING;
