-- Typed delivery, receipt, fulfillment, return, and stock-count documents.

ALTER TABLE fast_erp.sales_orders DROP CONSTRAINT IF EXISTS sales_orders_status_check;
ALTER TABLE fast_erp.sales_orders
    ADD CONSTRAINT sales_orders_status_check CHECK (status IN (
        'Draft', 'Confirmed', 'Partly Delivered', 'Delivered', 'Partly Invoiced',
        'Invoiced', 'On Hold', 'Closed', 'Cancelled'
    ));

ALTER TABLE fast_erp.purchase_orders DROP CONSTRAINT IF EXISTS purchase_orders_status_check;
ALTER TABLE fast_erp.purchase_orders
    ADD CONSTRAINT purchase_orders_status_check CHECK (status IN (
        'Draft', 'Ordered', 'Partly Received', 'Received', 'Partly Invoiced',
        'Invoiced', 'On Hold', 'Closed', 'Cancelled'
    ));

ALTER TABLE fast_erp.sales_order_items
    ADD COLUMN IF NOT EXISTS uom_id BIGINT REFERENCES fast_erp.uoms(id),
    ADD COLUMN IF NOT EXISTS stock_qty NUMERIC(20, 6),
    ADD COLUMN IF NOT EXISTS delivered_qty NUMERIC(20, 6) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS returned_qty NUMERIC(20, 6) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS invoiced_qty NUMERIC(20, 6) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS delivery_tolerance_percent NUMERIC(9, 6) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS billing_tolerance_percent NUMERIC(9, 6) NOT NULL DEFAULT 0;

ALTER TABLE fast_erp.purchase_order_items
    ADD COLUMN IF NOT EXISTS uom_id BIGINT REFERENCES fast_erp.uoms(id),
    ADD COLUMN IF NOT EXISTS stock_qty NUMERIC(20, 6),
    ADD COLUMN IF NOT EXISTS received_qty NUMERIC(20, 6) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS returned_qty NUMERIC(20, 6) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS invoiced_qty NUMERIC(20, 6) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS receipt_tolerance_percent NUMERIC(9, 6) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS billing_tolerance_percent NUMERIC(9, 6) NOT NULL DEFAULT 0;

CREATE TABLE fast_erp.sales_deliveries (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    code            TEXT NOT NULL,
    customer_id     BIGINT REFERENCES fast_erp.customers(id),
    document_kind   TEXT NOT NULL DEFAULT 'Delivery'
                    CHECK (document_kind IN ('Delivery', 'Return')),
    delivery_date   DATE NOT NULL,
    document_state  TEXT NOT NULL DEFAULT 'Draft'
                    CHECK (document_state IN ('Draft', 'Pending Approval', 'Approved', 'Posted', 'Held', 'Closed', 'Cancelled')),
    status          TEXT NOT NULL DEFAULT 'Draft'
                    CHECK (status IN ('Draft', 'To Bill', 'Partly Billed', 'Completed', 'Return', 'Cancelled', 'Closed')),
    return_against_id BIGINT REFERENCES fast_erp.sales_deliveries(id),
    revision        INTEGER NOT NULL DEFAULT 1 CHECK (revision > 0),
    row_version     BIGINT NOT NULL DEFAULT 1,
    posted_at       TIMESTAMPTZ,
    posted_by       TEXT,
    cancelled_at    TIMESTAMPTZ,
    cancelled_by    TEXT,
    reversal_of_id  BIGINT REFERENCES fast_erp.sales_deliveries(id),
    note            TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (company_id, code),
    CHECK ((document_kind = 'Return') = (return_against_id IS NOT NULL))
);

CREATE TABLE fast_erp.sales_delivery_items (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delivery_id     BIGINT NOT NULL REFERENCES fast_erp.sales_deliveries(id) ON DELETE CASCADE,
    line_number     INTEGER NOT NULL,
    sales_order_item_id BIGINT REFERENCES fast_erp.sales_order_items(id),
    item_id         BIGINT NOT NULL REFERENCES fast_erp.items(id),
    warehouse_id    BIGINT NOT NULL REFERENCES fast_erp.warehouses(id),
    uom_id          BIGINT REFERENCES fast_erp.uoms(id),
    qty             NUMERIC(20, 6) NOT NULL CHECK (qty > 0),
    stock_qty       NUMERIC(20, 6) NOT NULL CHECK (stock_qty > 0),
    unit_cost       NUMERIC(20, 6),
    billed_qty      NUMERIC(20, 6) NOT NULL DEFAULT 0 CHECK (billed_qty >= 0),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (delivery_id, line_number)
);

CREATE TABLE fast_erp.purchase_receipts (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    code            TEXT NOT NULL,
    supplier_id     BIGINT REFERENCES fast_erp.suppliers(id),
    document_kind   TEXT NOT NULL DEFAULT 'Receipt'
                    CHECK (document_kind IN ('Receipt', 'Return')),
    receipt_date    DATE NOT NULL,
    document_state  TEXT NOT NULL DEFAULT 'Draft'
                    CHECK (document_state IN ('Draft', 'Pending Approval', 'Approved', 'Posted', 'Held', 'Closed', 'Cancelled')),
    status          TEXT NOT NULL DEFAULT 'Draft'
                    CHECK (status IN ('Draft', 'To Bill', 'Partly Billed', 'Completed', 'Return', 'Cancelled', 'Closed')),
    return_against_id BIGINT REFERENCES fast_erp.purchase_receipts(id),
    revision        INTEGER NOT NULL DEFAULT 1 CHECK (revision > 0),
    row_version     BIGINT NOT NULL DEFAULT 1,
    posted_at       TIMESTAMPTZ,
    posted_by       TEXT,
    cancelled_at    TIMESTAMPTZ,
    cancelled_by    TEXT,
    reversal_of_id  BIGINT REFERENCES fast_erp.purchase_receipts(id),
    note            TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (company_id, code),
    CHECK ((document_kind = 'Return') = (return_against_id IS NOT NULL))
);

CREATE TABLE fast_erp.purchase_receipt_items (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_id      BIGINT NOT NULL REFERENCES fast_erp.purchase_receipts(id) ON DELETE CASCADE,
    line_number     INTEGER NOT NULL,
    purchase_order_item_id BIGINT REFERENCES fast_erp.purchase_order_items(id),
    item_id         BIGINT NOT NULL REFERENCES fast_erp.items(id),
    accepted_warehouse_id BIGINT REFERENCES fast_erp.warehouses(id),
    rejected_warehouse_id BIGINT REFERENCES fast_erp.warehouses(id),
    uom_id          BIGINT REFERENCES fast_erp.uoms(id),
    accepted_qty    NUMERIC(20, 6) NOT NULL DEFAULT 0 CHECK (accepted_qty >= 0),
    rejected_qty    NUMERIC(20, 6) NOT NULL DEFAULT 0 CHECK (rejected_qty >= 0),
    stock_qty       NUMERIC(20, 6) NOT NULL CHECK (stock_qty > 0),
    unit_cost       NUMERIC(20, 6),
    billed_qty      NUMERIC(20, 6) NOT NULL DEFAULT 0 CHECK (billed_qty >= 0),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (receipt_id, line_number),
    CHECK (accepted_qty + rejected_qty > 0),
    CHECK (accepted_qty = 0 OR accepted_warehouse_id IS NOT NULL),
    CHECK (rejected_qty = 0 OR rejected_warehouse_id IS NOT NULL)
);

CREATE TABLE fast_erp.stock_counts (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    code            TEXT NOT NULL,
    warehouse_id    BIGINT NOT NULL REFERENCES fast_erp.warehouses(id),
    count_date      DATE NOT NULL,
    document_state  TEXT NOT NULL DEFAULT 'Draft'
                    CHECK (document_state IN ('Draft', 'Pending Approval', 'Approved', 'Posted', 'Cancelled')),
    posted_at       TIMESTAMPTZ,
    posted_by       TEXT,
    note            TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (company_id, code)
);

CREATE TABLE fast_erp.stock_count_items (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_count_id  BIGINT NOT NULL REFERENCES fast_erp.stock_counts(id) ON DELETE CASCADE,
    line_number     INTEGER NOT NULL,
    item_id         BIGINT NOT NULL REFERENCES fast_erp.items(id),
    system_qty      NUMERIC(20, 6) NOT NULL,
    counted_qty     NUMERIC(20, 6) NOT NULL CHECK (counted_qty >= 0),
    system_value    NUMERIC(20, 6) NOT NULL,
    counted_value   NUMERIC(20, 6) NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (stock_count_id, line_number)
);

CREATE INDEX idx_sales_deliveries_company_date ON fast_erp.sales_deliveries (company_id, delivery_date, status);
CREATE INDEX idx_sales_delivery_order_line ON fast_erp.sales_delivery_items (sales_order_item_id);
CREATE INDEX idx_purchase_receipts_company_date ON fast_erp.purchase_receipts (company_id, receipt_date, status);
CREATE INDEX idx_purchase_receipt_order_line ON fast_erp.purchase_receipt_items (purchase_order_item_id);

INSERT INTO fast_erp.schema_migrations (version)
VALUES ('0004_logistics_documents')
ON CONFLICT (version) DO NOTHING;
