-- AR/AP documents, payments, advances, party ledger, and allocations.

ALTER TABLE fast_erp.invoices
    ADD COLUMN IF NOT EXISTS invoice_type TEXT NOT NULL DEFAULT 'Invoice',
    ADD COLUMN IF NOT EXISTS return_against_id BIGINT REFERENCES fast_erp.invoices(id),
    ADD COLUMN IF NOT EXISTS payment_term_id BIGINT REFERENCES fast_erp.payment_terms(id),
    ADD COLUMN IF NOT EXISTS base_net_total NUMERIC(20, 4),
    ADD COLUMN IF NOT EXISTS base_tax_total NUMERIC(20, 4),
    ADD COLUMN IF NOT EXISTS base_total NUMERIC(20, 4),
    ADD COLUMN IF NOT EXISTS outstanding_amount NUMERIC(20, 4) NOT NULL DEFAULT 0;

ALTER TABLE fast_erp.invoices
    ADD CONSTRAINT invoices_type_check CHECK (invoice_type IN ('Invoice', 'Credit Note')),
    ADD CONSTRAINT invoices_return_check CHECK ((invoice_type = 'Credit Note') = (return_against_id IS NOT NULL));

UPDATE fast_erp.invoices
   SET base_net_total = COALESCE(base_net_total, net_total * exchange_rate),
       base_tax_total = COALESCE(base_tax_total, tax_total * exchange_rate),
       base_total = COALESCE(base_total, total * exchange_rate),
       outstanding_amount = GREATEST(total - paid, 0);

ALTER TABLE fast_erp.invoice_items
    ADD COLUMN IF NOT EXISTS sales_order_item_id BIGINT REFERENCES fast_erp.sales_order_items(id),
    ADD COLUMN IF NOT EXISTS delivery_item_id BIGINT REFERENCES fast_erp.sales_delivery_items(id),
    ADD COLUMN IF NOT EXISTS uom_id BIGINT REFERENCES fast_erp.uoms(id),
    ADD COLUMN IF NOT EXISTS stock_qty NUMERIC(20, 6),
    ADD COLUMN IF NOT EXISTS base_net_amount NUMERIC(20, 4),
    ADD COLUMN IF NOT EXISTS base_tax_amount NUMERIC(20, 4),
    ADD COLUMN IF NOT EXISTS base_amount NUMERIC(20, 4);

CREATE TABLE fast_erp.purchase_invoices (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    code            TEXT NOT NULL,
    supplier_id     BIGINT REFERENCES fast_erp.suppliers(id),
    invoice_type    TEXT NOT NULL DEFAULT 'Invoice'
                    CHECK (invoice_type IN ('Invoice', 'Debit Note')),
    supplier_reference TEXT,
    invoice_date    DATE NOT NULL,
    due_date        DATE,
    currency        CHAR(3) NOT NULL REFERENCES fast_erp.currencies(code),
    exchange_rate   NUMERIC(20, 10) NOT NULL DEFAULT 1 CHECK (exchange_rate > 0),
    net_total       NUMERIC(20, 4) NOT NULL DEFAULT 0 CHECK (net_total >= 0),
    tax_total       NUMERIC(20, 4) NOT NULL DEFAULT 0 CHECK (tax_total >= 0),
    total           NUMERIC(20, 4) NOT NULL DEFAULT 0 CHECK (total >= 0),
    base_net_total  NUMERIC(20, 4) NOT NULL DEFAULT 0 CHECK (base_net_total >= 0),
    base_tax_total  NUMERIC(20, 4) NOT NULL DEFAULT 0 CHECK (base_tax_total >= 0),
    base_total      NUMERIC(20, 4) NOT NULL DEFAULT 0 CHECK (base_total >= 0),
    outstanding_amount NUMERIC(20, 4) NOT NULL DEFAULT 0 CHECK (outstanding_amount >= 0),
    payment_term_id BIGINT REFERENCES fast_erp.payment_terms(id),
    return_against_id BIGINT REFERENCES fast_erp.purchase_invoices(id),
    document_state  TEXT NOT NULL DEFAULT 'Draft'
                    CHECK (document_state IN ('Draft', 'Pending Approval', 'Approved', 'Posted', 'Held', 'Closed', 'Cancelled')),
    status          TEXT NOT NULL DEFAULT 'Unpaid'
                    CHECK (status IN ('Unpaid', 'Partly Paid', 'Paid', 'Overdue', 'Held', 'Cancelled')),
    revision        INTEGER NOT NULL DEFAULT 1 CHECK (revision > 0),
    row_version     BIGINT NOT NULL DEFAULT 1,
    posted_at       TIMESTAMPTZ,
    posted_by       TEXT,
    cancelled_at    TIMESTAMPTZ,
    cancelled_by    TEXT,
    reversal_of_id  BIGINT REFERENCES fast_erp.purchase_invoices(id),
    note            TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (company_id, code),
    CHECK (due_date IS NULL OR due_date >= invoice_date),
    CHECK ((invoice_type = 'Debit Note') = (return_against_id IS NOT NULL))
);

CREATE TABLE fast_erp.purchase_invoice_items (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_invoice_id BIGINT NOT NULL REFERENCES fast_erp.purchase_invoices(id) ON DELETE CASCADE,
    line_number     INTEGER NOT NULL,
    purchase_order_item_id BIGINT REFERENCES fast_erp.purchase_order_items(id),
    receipt_item_id BIGINT REFERENCES fast_erp.purchase_receipt_items(id),
    item_id         BIGINT REFERENCES fast_erp.items(id),
    warehouse_id    BIGINT REFERENCES fast_erp.warehouses(id),
    expense_account_id BIGINT REFERENCES fast_erp.accounts(id),
    description     TEXT,
    uom_id          BIGINT REFERENCES fast_erp.uoms(id),
    qty             NUMERIC(20, 6) NOT NULL CHECK (qty >= 0),
    stock_qty       NUMERIC(20, 6),
    rate            NUMERIC(20, 6) NOT NULL CHECK (rate >= 0),
    net_amount      NUMERIC(20, 4) NOT NULL CHECK (net_amount >= 0),
    tax_amount      NUMERIC(20, 4) NOT NULL DEFAULT 0 CHECK (tax_amount >= 0),
    amount          NUMERIC(20, 4) NOT NULL CHECK (amount >= 0),
    base_net_amount NUMERIC(20, 4) NOT NULL CHECK (base_net_amount >= 0),
    base_tax_amount NUMERIC(20, 4) NOT NULL CHECK (base_tax_amount >= 0),
    base_amount     NUMERIC(20, 4) NOT NULL CHECK (base_amount >= 0),
    tax_code_id     BIGINT REFERENCES fast_erp.tax_codes(id),
    business_unit_id BIGINT REFERENCES fast_erp.business_units(id),
    project_id      BIGINT REFERENCES fast_erp.projects(id),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (purchase_invoice_id, line_number)
);

ALTER TABLE fast_erp.payments
    ADD COLUMN IF NOT EXISTS payment_type TEXT NOT NULL DEFAULT 'Customer Receipt',
    ADD COLUMN IF NOT EXISTS supplier_id BIGINT REFERENCES fast_erp.suppliers(id),
    ADD COLUMN IF NOT EXISTS bank_account_id BIGINT REFERENCES fast_erp.bank_accounts(id),
    ADD COLUMN IF NOT EXISTS base_amount NUMERIC(20, 4),
    ADD COLUMN IF NOT EXISTS unallocated_amount NUMERIC(20, 4) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS reference_number TEXT,
    ADD COLUMN IF NOT EXISTS reference_date DATE;

ALTER TABLE fast_erp.payments
    ADD CONSTRAINT payments_type_check CHECK (payment_type IN ('Customer Receipt', 'Supplier Payment', 'Internal Transfer')),
    ADD CONSTRAINT payments_party_check CHECK (
        (payment_type = 'Customer Receipt' AND customer_id IS NOT NULL AND supplier_id IS NULL)
        OR (payment_type = 'Supplier Payment' AND supplier_id IS NOT NULL AND customer_id IS NULL)
        OR (payment_type = 'Internal Transfer' AND customer_id IS NULL AND supplier_id IS NULL)
    );

UPDATE fast_erp.payments payment
   SET base_amount = COALESCE(base_amount, amount * exchange_rate),
       unallocated_amount = GREATEST(
           amount - COALESCE((
               SELECT sum(allocation.amount)
                 FROM fast_erp.payment_allocations allocation
                WHERE allocation.payment_id = payment.id
           ), 0),
           0
       );

CREATE TABLE fast_erp.supplier_payment_allocations (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id      BIGINT NOT NULL REFERENCES fast_erp.payments(id) ON DELETE CASCADE,
    purchase_invoice_id BIGINT NOT NULL REFERENCES fast_erp.purchase_invoices(id),
    amount          NUMERIC(20, 4) NOT NULL CHECK (amount > 0),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (payment_id, purchase_invoice_id)
);

CREATE TABLE fast_erp.party_ledger_entries (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    partner_id      BIGINT NOT NULL REFERENCES fast_erp.business_partners(id),
    partner_role    TEXT NOT NULL CHECK (partner_role IN ('Customer', 'Supplier')),
    posting_date    DATE NOT NULL,
    due_date        DATE,
    voucher_type    TEXT NOT NULL,
    voucher_id      BIGINT NOT NULL,
    voucher_code    TEXT NOT NULL,
    currency        CHAR(3) NOT NULL REFERENCES fast_erp.currencies(code),
    debit           NUMERIC(20, 4) NOT NULL DEFAULT 0 CHECK (debit >= 0),
    credit          NUMERIC(20, 4) NOT NULL DEFAULT 0 CHECK (credit >= 0),
    base_debit      NUMERIC(20, 4) NOT NULL DEFAULT 0 CHECK (base_debit >= 0),
    base_credit     NUMERIC(20, 4) NOT NULL DEFAULT 0 CHECK (base_credit >= 0),
    is_advance      BOOLEAN NOT NULL DEFAULT false,
    reverses_entry_id BIGINT REFERENCES fast_erp.party_ledger_entries(id),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK ((debit > 0 AND credit = 0) OR (credit > 0 AND debit = 0)),
    CHECK ((base_debit > 0 AND base_credit = 0) OR (base_credit > 0 AND base_debit = 0)),
    UNIQUE (company_id, voucher_type, voucher_id, partner_role)
);

CREATE TABLE fast_erp.party_ledger_allocations (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    source_entry_id BIGINT NOT NULL REFERENCES fast_erp.party_ledger_entries(id),
    target_entry_id BIGINT NOT NULL REFERENCES fast_erp.party_ledger_entries(id),
    allocation_date DATE NOT NULL,
    amount          NUMERIC(20, 4) NOT NULL CHECK (amount > 0),
    base_amount     NUMERIC(20, 4) NOT NULL CHECK (base_amount > 0),
    exchange_gain_loss NUMERIC(20, 4) NOT NULL DEFAULT 0,
    reversed_by_id  BIGINT REFERENCES fast_erp.party_ledger_allocations(id),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (source_entry_id <> target_entry_id)
);

CREATE TABLE fast_erp.payment_schedules (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type     TEXT NOT NULL CHECK (entity_type IN ('Sales Invoice', 'Purchase Invoice')),
    entity_id       BIGINT NOT NULL,
    installment_number INTEGER NOT NULL CHECK (installment_number > 0),
    due_date        DATE NOT NULL,
    amount          NUMERIC(20, 4) NOT NULL CHECK (amount > 0),
    discount_date   DATE,
    discount_amount NUMERIC(20, 4),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (entity_type, entity_id, installment_number)
);

CREATE INDEX idx_purchase_invoices_company_status ON fast_erp.purchase_invoices (company_id, status, invoice_date);
CREATE INDEX idx_party_ledger_partner_date ON fast_erp.party_ledger_entries (company_id, partner_id, posting_date);
CREATE INDEX idx_party_alloc_source ON fast_erp.party_ledger_allocations (source_entry_id);
CREATE INDEX idx_party_alloc_target ON fast_erp.party_ledger_allocations (target_entry_id);

INSERT INTO fast_erp.schema_migrations (version)
VALUES ('0005_receivables_payables')
ON CONFLICT (version) DO NOTHING;
