-- Immutable inventory events, valuation ledger, balances, serials, and batches.

CREATE TABLE fast_erp.inventory_events (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    event_type      TEXT NOT NULL CHECK (event_type IN (
        'Opening', 'Receipt', 'Delivery', 'Purchase Return', 'Sales Return',
        'Transfer', 'Adjustment', 'Stock Count', 'Landed Cost', 'Revaluation'
    )),
    event_date      DATE NOT NULL,
    posting_time    TIME NOT NULL DEFAULT localtime,
    sequence_no     BIGINT NOT NULL,
    voucher_type    TEXT NOT NULL,
    voucher_id      BIGINT NOT NULL,
    voucher_code    TEXT NOT NULL,
    document_state  TEXT NOT NULL DEFAULT 'Posted'
                    CHECK (document_state IN ('Draft', 'Posted', 'Cancelled')),
    reverses_event_id BIGINT REFERENCES fast_erp.inventory_events(id),
    posted_at       TIMESTAMPTZ,
    posted_by       TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (company_id, sequence_no),
    UNIQUE (company_id, voucher_type, voucher_id, event_type)
);

CREATE TABLE fast_erp.inventory_event_lines (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id        BIGINT NOT NULL REFERENCES fast_erp.inventory_events(id) ON DELETE CASCADE,
    line_number     INTEGER NOT NULL,
    item_id         BIGINT NOT NULL REFERENCES fast_erp.items(id),
    warehouse_id    BIGINT NOT NULL REFERENCES fast_erp.warehouses(id),
    offset_warehouse_id BIGINT REFERENCES fast_erp.warehouses(id),
    quantity        NUMERIC(20, 6) NOT NULL CHECK (quantity <> 0),
    unit_cost       NUMERIC(20, 6),
    additional_cost NUMERIC(20, 6) NOT NULL DEFAULT 0,
    source_line_type TEXT,
    source_line_id  BIGINT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (event_id, line_number)
);

CREATE TABLE fast_erp.inventory_ledger_entries (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    event_id        BIGINT NOT NULL REFERENCES fast_erp.inventory_events(id),
    event_line_id   BIGINT NOT NULL REFERENCES fast_erp.inventory_event_lines(id),
    item_id         BIGINT NOT NULL REFERENCES fast_erp.items(id),
    warehouse_id    BIGINT NOT NULL REFERENCES fast_erp.warehouses(id),
    posting_at      TIMESTAMPTZ NOT NULL,
    sequence_no     BIGINT NOT NULL,
    quantity_change NUMERIC(20, 6) NOT NULL CHECK (quantity_change <> 0),
    quantity_after  NUMERIC(20, 6) NOT NULL,
    incoming_rate   NUMERIC(20, 6),
    outgoing_rate   NUMERIC(20, 6),
    valuation_rate  NUMERIC(20, 6) NOT NULL,
    value_change    NUMERIC(20, 6) NOT NULL,
    value_after     NUMERIC(20, 6) NOT NULL,
    valuation_method TEXT NOT NULL CHECK (valuation_method IN ('Moving Average', 'FIFO', 'Standard Cost')),
    cost_queue      JSONB,
    reverses_entry_id BIGINT REFERENCES fast_erp.inventory_ledger_entries(id),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (company_id, sequence_no),
    UNIQUE (event_line_id)
);

CREATE TABLE fast_erp.inventory_balances (
    company_id      BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    item_id         BIGINT NOT NULL REFERENCES fast_erp.items(id),
    warehouse_id    BIGINT NOT NULL REFERENCES fast_erp.warehouses(id),
    quantity        NUMERIC(20, 6) NOT NULL DEFAULT 0,
    inventory_value NUMERIC(20, 6) NOT NULL DEFAULT 0,
    valuation_rate  NUMERIC(20, 6) NOT NULL DEFAULT 0,
    last_ledger_entry_id BIGINT REFERENCES fast_erp.inventory_ledger_entries(id),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (company_id, item_id, warehouse_id)
);

CREATE TABLE fast_erp.inventory_cost_layers (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    item_id         BIGINT NOT NULL REFERENCES fast_erp.items(id),
    warehouse_id    BIGINT NOT NULL REFERENCES fast_erp.warehouses(id),
    source_ledger_entry_id BIGINT NOT NULL REFERENCES fast_erp.inventory_ledger_entries(id),
    received_at     TIMESTAMPTZ NOT NULL,
    original_qty    NUMERIC(20, 6) NOT NULL CHECK (original_qty > 0),
    remaining_qty   NUMERIC(20, 6) NOT NULL CHECK (remaining_qty >= 0),
    unit_cost       NUMERIC(20, 6) NOT NULL CHECK (unit_cost >= 0),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (remaining_qty <= original_qty)
);

CREATE TABLE fast_erp.batches (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    item_id         BIGINT NOT NULL REFERENCES fast_erp.items(id),
    batch_code      TEXT NOT NULL,
    manufactured_on DATE,
    expires_on      DATE,
    supplier_id     BIGINT REFERENCES fast_erp.suppliers(id),
    active          BOOLEAN NOT NULL DEFAULT true,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (company_id, item_id, batch_code),
    CHECK (expires_on IS NULL OR manufactured_on IS NULL OR expires_on >= manufactured_on)
);

CREATE TABLE fast_erp.serial_numbers (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    item_id         BIGINT NOT NULL REFERENCES fast_erp.items(id),
    serial_code     TEXT NOT NULL,
    batch_id        BIGINT REFERENCES fast_erp.batches(id),
    warehouse_id    BIGINT REFERENCES fast_erp.warehouses(id),
    status          TEXT NOT NULL DEFAULT 'Available'
                    CHECK (status IN ('Available', 'Delivered', 'Returned', 'Consumed', 'Inactive')),
    purchase_date   DATE,
    warranty_expires_on DATE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (company_id, serial_code)
);

CREATE TABLE fast_erp.inventory_tracking_entries (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ledger_entry_id BIGINT NOT NULL REFERENCES fast_erp.inventory_ledger_entries(id),
    batch_id        BIGINT REFERENCES fast_erp.batches(id),
    serial_number_id BIGINT REFERENCES fast_erp.serial_numbers(id),
    quantity        NUMERIC(20, 6) NOT NULL CHECK (quantity <> 0),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK ((batch_id IS NOT NULL) OR (serial_number_id IS NOT NULL))
);

CREATE TABLE fast_erp.landed_cost_documents (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    code            TEXT NOT NULL,
    posting_date    DATE NOT NULL,
    currency        CHAR(3) NOT NULL REFERENCES fast_erp.currencies(code),
    exchange_rate   NUMERIC(20, 10) NOT NULL CHECK (exchange_rate > 0),
    total_cost      NUMERIC(20, 4) NOT NULL CHECK (total_cost > 0),
    allocation_method TEXT NOT NULL CHECK (allocation_method IN ('Quantity', 'Value')),
    document_state  TEXT NOT NULL DEFAULT 'Draft'
                    CHECK (document_state IN ('Draft', 'Posted', 'Cancelled')),
    posted_at       TIMESTAMPTZ,
    posted_by       TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (company_id, code)
);

CREATE TABLE fast_erp.landed_cost_allocations (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    landed_cost_id  BIGINT NOT NULL REFERENCES fast_erp.landed_cost_documents(id) ON DELETE CASCADE,
    receipt_item_id BIGINT NOT NULL REFERENCES fast_erp.purchase_receipt_items(id),
    allocated_amount NUMERIC(20, 4) NOT NULL CHECK (allocated_amount > 0),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (landed_cost_id, receipt_item_id)
);

CREATE OR REPLACE FUNCTION fast_erp.reject_immutable_ledger_mutation()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION '% is immutable; create a reversing entry instead', TG_TABLE_NAME
        USING ERRCODE = '55000';
END;
$$;

CREATE TRIGGER inventory_ledger_immutable_update
BEFORE UPDATE OR DELETE ON fast_erp.inventory_ledger_entries
FOR EACH ROW EXECUTE FUNCTION fast_erp.reject_immutable_ledger_mutation();

CREATE INDEX idx_inventory_ledger_balance_order
    ON fast_erp.inventory_ledger_entries (company_id, item_id, warehouse_id, posting_at, sequence_no);
CREATE INDEX idx_inventory_cost_layers_open
    ON fast_erp.inventory_cost_layers (company_id, item_id, warehouse_id, received_at)
    WHERE remaining_qty > 0;
CREATE INDEX idx_batches_expiry ON fast_erp.batches (company_id, item_id, expires_on);
CREATE INDEX idx_serial_current ON fast_erp.serial_numbers (company_id, item_id, warehouse_id, status);

INSERT INTO fast_erp.schema_migrations (version)
VALUES ('0006_inventory_ledger')
ON CONFLICT (version) DO NOTHING;
