-- Posting batches, currency-complete GL, voucher links, and immutable entries.

CREATE TABLE fast_erp.posting_batches (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    voucher_type    TEXT NOT NULL,
    voucher_id      BIGINT NOT NULL,
    voucher_code    TEXT NOT NULL,
    posting_date    DATE NOT NULL,
    status          TEXT NOT NULL DEFAULT 'Draft'
                    CHECK (status IN ('Draft', 'Posted', 'Reversed')),
    reverses_batch_id BIGINT REFERENCES fast_erp.posting_batches(id),
    posted_at       TIMESTAMPTZ,
    posted_by       TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (company_id, voucher_type, voucher_id),
    CHECK ((status = 'Posted') = (posted_at IS NOT NULL) OR status = 'Reversed')
);

ALTER TABLE fast_erp.companies
    ADD COLUMN IF NOT EXISTS reporting_currency CHAR(3) REFERENCES fast_erp.currencies(code),
    ADD COLUMN IF NOT EXISTS negative_stock_allowed BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE fast_erp.journal_entries
    ADD COLUMN IF NOT EXISTS transaction_currency CHAR(3) REFERENCES fast_erp.currencies(code),
    ADD COLUMN IF NOT EXISTS transaction_exchange_rate NUMERIC(20, 10),
    ADD COLUMN IF NOT EXISTS posting_batch_id BIGINT REFERENCES fast_erp.posting_batches(id);

ALTER TABLE fast_erp.journal_lines
    ADD COLUMN IF NOT EXISTS transaction_debit NUMERIC(20, 4) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS transaction_credit NUMERIC(20, 4) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS account_currency CHAR(3) REFERENCES fast_erp.currencies(code),
    ADD COLUMN IF NOT EXISTS account_debit NUMERIC(20, 4) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS account_credit NUMERIC(20, 4) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS party_id BIGINT REFERENCES fast_erp.business_partners(id),
    ADD COLUMN IF NOT EXISTS due_date DATE;

ALTER TABLE fast_erp.gl_entries
    ADD COLUMN IF NOT EXISTS posting_batch_id BIGINT REFERENCES fast_erp.posting_batches(id),
    ADD COLUMN IF NOT EXISTS line_number INTEGER,
    ADD COLUMN IF NOT EXISTS voucher_type TEXT,
    ADD COLUMN IF NOT EXISTS voucher_id BIGINT,
    ADD COLUMN IF NOT EXISTS voucher_code TEXT,
    ADD COLUMN IF NOT EXISTS party_id BIGINT REFERENCES fast_erp.business_partners(id),
    ADD COLUMN IF NOT EXISTS due_date DATE,
    ADD COLUMN IF NOT EXISTS account_currency CHAR(3) REFERENCES fast_erp.currencies(code),
    ADD COLUMN IF NOT EXISTS account_debit NUMERIC(20, 4) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS account_credit NUMERIC(20, 4) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS transaction_currency CHAR(3) REFERENCES fast_erp.currencies(code),
    ADD COLUMN IF NOT EXISTS transaction_exchange_rate NUMERIC(20, 10),
    ADD COLUMN IF NOT EXISTS transaction_debit NUMERIC(20, 4) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS transaction_credit NUMERIC(20, 4) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS reporting_currency CHAR(3) REFERENCES fast_erp.currencies(code),
    ADD COLUMN IF NOT EXISTS reporting_exchange_rate NUMERIC(20, 10),
    ADD COLUMN IF NOT EXISTS reporting_debit NUMERIC(20, 4) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS reporting_credit NUMERIC(20, 4) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS reverses_entry_id BIGINT REFERENCES fast_erp.gl_entries(id),
    ADD COLUMN IF NOT EXISTS source_line_type TEXT,
    ADD COLUMN IF NOT EXISTS source_line_id BIGINT;

CREATE TABLE fast_erp.accounting_reposts (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    requested_for   DATE NOT NULL,
    reason          TEXT NOT NULL,
    status          TEXT NOT NULL DEFAULT 'Queued'
                    CHECK (status IN ('Queued', 'Running', 'Completed', 'Failed')),
    requested_by    TEXT NOT NULL,
    started_at      TIMESTAMPTZ,
    completed_at    TIMESTAMPTZ,
    details         JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE OR REPLACE FUNCTION fast_erp.assert_posting_batch_balanced()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    debit_total NUMERIC(30, 4);
    credit_total NUMERIC(30, 4);
    line_count BIGINT;
BEGIN
    IF NEW.status = 'Posted' AND OLD.status IS DISTINCT FROM 'Posted' THEN
        SELECT COALESCE(sum(debit), 0), COALESCE(sum(credit), 0), count(*)
          INTO debit_total, credit_total, line_count
          FROM fast_erp.gl_entries
         WHERE posting_batch_id = NEW.id;
        IF line_count < 2 OR debit_total <> credit_total OR debit_total = 0 THEN
            RAISE EXCEPTION 'posting batch % is not balanced: debit %, credit %, lines %',
                NEW.id, debit_total, credit_total, line_count
                USING ERRCODE = '23514';
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER posting_batch_balance_check
BEFORE UPDATE OF status ON fast_erp.posting_batches
FOR EACH ROW EXECUTE FUNCTION fast_erp.assert_posting_batch_balanced();

CREATE TRIGGER gl_entries_immutable_update
BEFORE UPDATE OR DELETE ON fast_erp.gl_entries
FOR EACH ROW EXECUTE FUNCTION fast_erp.reject_immutable_ledger_mutation();

CREATE TRIGGER party_ledger_immutable_update
BEFORE UPDATE OR DELETE ON fast_erp.party_ledger_entries
FOR EACH ROW EXECUTE FUNCTION fast_erp.reject_immutable_ledger_mutation();

CREATE INDEX idx_posting_batches_voucher ON fast_erp.posting_batches (company_id, voucher_type, voucher_code);
CREATE INDEX idx_gl_posting_batch ON fast_erp.gl_entries (posting_batch_id, line_number);
CREATE INDEX idx_gl_voucher ON fast_erp.gl_entries (company_id, voucher_type, voucher_id);
CREATE INDEX idx_gl_party_due ON fast_erp.gl_entries (company_id, party_id, due_date);

INSERT INTO fast_erp.schema_migrations (version)
VALUES ('0007_accounting_kernel')
ON CONFLICT (version) DO NOTHING;
