-- Connector capabilities, dependencies, archival, apply manifests, and cutover evidence.

ALTER TABLE fast_erp.migration_sources DROP CONSTRAINT IF EXISTS migration_sources_connector_type_check;
ALTER TABLE fast_erp.migration_sources
    ADD CONSTRAINT migration_sources_connector_type_check CHECK (connector_type IN (
        'sap_business_one_odata_v4', 'erpnext_rest', 'sap_s4_odata', 'sap_ecc',
        'csv_bundle', 'mock_sap'
    ));

ALTER TABLE fast_erp.migration_runs DROP CONSTRAINT IF EXISTS migration_runs_status_check;
ALTER TABLE fast_erp.migration_runs
    ADD CONSTRAINT migration_runs_status_check CHECK (status IN (
        'Created', 'Discovering', 'Discovered', 'Extracting', 'Staged',
        'Validating', 'Validated', 'Approved', 'Applying', 'Reconciling',
        'Completed', 'Failed', 'Cancelled', 'Rolled Back'
    ));

ALTER TABLE fast_erp.migration_staging_records DROP CONSTRAINT IF EXISTS migration_staging_records_status_check;
ALTER TABLE fast_erp.migration_staging_records
    ADD CONSTRAINT migration_staging_records_status_check CHECK (status IN (
        'Extracted', 'Mapped', 'Valid', 'Warning', 'Invalid', 'Applied',
        'Archived', 'Skipped', 'Failed'
    ));

ALTER TABLE fast_erp.migration_runs
    ADD COLUMN IF NOT EXISTS source_snapshot_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS manifest_hash TEXT,
    ADD COLUMN IF NOT EXISTS cutover_started_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS cutover_completed_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS rollback_reference TEXT;

ALTER TABLE fast_erp.migration_staging_records
    ADD COLUMN IF NOT EXISTS dependencies JSONB NOT NULL DEFAULT '[]'::jsonb,
    ADD COLUMN IF NOT EXISTS archived_reason TEXT,
    ADD COLUMN IF NOT EXISTS apply_attempts INTEGER NOT NULL DEFAULT 0;

CREATE TABLE fast_erp.migration_source_capabilities (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id       BIGINT NOT NULL REFERENCES fast_erp.migration_sources(id) ON DELETE CASCADE,
    source_object   TEXT NOT NULL,
    available       BOOLEAN NOT NULL,
    supports_filter BOOLEAN NOT NULL DEFAULT false,
    supports_expand BOOLEAN NOT NULL DEFAULT false,
    key_fields      JSONB NOT NULL DEFAULT '[]'::jsonb,
    fields          JSONB NOT NULL DEFAULT '[]'::jsonb,
    estimated_count BIGINT,
    discovered_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    metadata_hash   TEXT,
    UNIQUE (source_id, source_object)
);

CREATE TABLE fast_erp.migration_object_dependencies (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_type     TEXT NOT NULL,
    source_object   TEXT NOT NULL,
    depends_on_object TEXT NOT NULL,
    required        BOOLEAN NOT NULL DEFAULT true,
    apply_order     INTEGER NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (source_type, source_object, depends_on_object),
    CHECK (source_object <> depends_on_object)
);

CREATE TABLE fast_erp.migration_apply_manifests (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id          BIGINT NOT NULL REFERENCES fast_erp.migration_runs(id) ON DELETE CASCADE,
    sequence_number INTEGER NOT NULL CHECK (sequence_number >= 0),
    source_object   TEXT NOT NULL,
    source_key      TEXT NOT NULL,
    staging_record_id BIGINT NOT NULL REFERENCES fast_erp.migration_staging_records(id),
    target_entity_type TEXT,
    target_entity_id BIGINT,
    action          TEXT NOT NULL CHECK (action IN ('Insert', 'Link', 'Archive', 'Skip', 'Reverse')),
    status          TEXT NOT NULL CHECK (status IN ('Planned', 'Applied', 'Failed', 'Rolled Back')),
    payload_hash    TEXT NOT NULL,
    error_details   JSONB,
    applied_at      TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (run_id, sequence_number),
    UNIQUE (run_id, source_object, source_key)
);

CREATE TABLE fast_erp.migration_archived_objects (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id          BIGINT NOT NULL REFERENCES fast_erp.migration_runs(id) ON DELETE CASCADE,
    source_id       BIGINT NOT NULL REFERENCES fast_erp.migration_sources(id),
    source_object   TEXT NOT NULL,
    source_key      TEXT NOT NULL,
    source_document_no TEXT,
    payload         JSONB NOT NULL,
    payload_hash    TEXT NOT NULL,
    archive_reason  TEXT NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (source_id, source_object, source_key, payload_hash)
);

CREATE TABLE fast_erp.migration_reconciliation_artifacts (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id          BIGINT NOT NULL REFERENCES fast_erp.migration_runs(id) ON DELETE CASCADE,
    artifact_type   TEXT NOT NULL CHECK (artifact_type IN (
        'Manifest', 'Counts', 'AR Aging', 'AP Aging', 'Inventory',
        'Trial Balance', 'Tax', 'Warnings', 'Backup', 'Rollback'
    )),
    content_type    TEXT NOT NULL,
    storage_path    TEXT,
    content_hash    TEXT NOT NULL,
    summary         JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (run_id, artifact_type, content_hash)
);

CREATE TABLE fast_erp.synthetic_fixture_manifests (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fixture_version TEXT NOT NULL UNIQUE,
    random_seed     BIGINT NOT NULL,
    company_count   INTEGER NOT NULL CHECK (company_count = 3),
    items_per_company INTEGER NOT NULL CHECK (items_per_company >= 1000),
    partners_per_company INTEGER NOT NULL CHECK (partners_per_company >= 3),
    rows_per_company INTEGER NOT NULL CHECK (rows_per_company >= 1000),
    currencies      JSONB NOT NULL,
    expected_results JSONB NOT NULL,
    manifest_hash   TEXT NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_migration_capabilities_source ON fast_erp.migration_source_capabilities (source_id, available);
CREATE INDEX idx_migration_apply_status ON fast_erp.migration_apply_manifests (run_id, status, sequence_number);
CREATE INDEX idx_migration_archive_lookup ON fast_erp.migration_archived_objects (source_id, source_object, source_key);

INSERT INTO fast_erp.schema_migrations (version)
VALUES ('0008_migration_extensions')
ON CONFLICT (version) DO NOTHING;
