-- Open quotation/RFQ workflow and currency-complete payment allocation.

CREATE TABLE fast_erp.company_accounting_settings (
    company_id          BIGINT PRIMARY KEY REFERENCES fast_erp.companies(id) ON DELETE CASCADE,
    receivable_account_id BIGINT REFERENCES fast_erp.accounts(id),
    payable_account_id  BIGINT REFERENCES fast_erp.accounts(id),
    inventory_account_id BIGINT REFERENCES fast_erp.accounts(id),
    cogs_account_id     BIGINT REFERENCES fast_erp.accounts(id),
    sales_account_id    BIGINT REFERENCES fast_erp.accounts(id),
    purchase_account_id BIGINT REFERENCES fast_erp.accounts(id),
    sales_tax_account_id BIGINT REFERENCES fast_erp.accounts(id),
    purchase_tax_account_id BIGINT REFERENCES fast_erp.accounts(id),
    exchange_gain_account_id BIGINT REFERENCES fast_erp.accounts(id),
    exchange_loss_account_id BIGINT REFERENCES fast_erp.accounts(id),
    default_bank_account_id BIGINT REFERENCES fast_erp.bank_accounts(id),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE fast_erp.sales_quotes (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    code            TEXT NOT NULL,
    customer_id     BIGINT REFERENCES fast_erp.customers(id),
    quote_date      DATE NOT NULL,
    valid_until     DATE,
    currency        CHAR(3) NOT NULL REFERENCES fast_erp.currencies(code),
    exchange_rate   NUMERIC(20, 10) NOT NULL DEFAULT 1 CHECK (exchange_rate > 0),
    net_total       NUMERIC(20, 4) NOT NULL DEFAULT 0 CHECK (net_total >= 0),
    tax_total       NUMERIC(20, 4) NOT NULL DEFAULT 0 CHECK (tax_total >= 0),
    total           NUMERIC(20, 4) NOT NULL DEFAULT 0 CHECK (total >= 0),
    document_state  TEXT NOT NULL DEFAULT 'Draft'
                    CHECK (document_state IN ('Draft', 'Pending Approval', 'Approved', 'Posted', 'Closed', 'Cancelled')),
    status          TEXT NOT NULL DEFAULT 'Open'
                    CHECK (status IN ('Open', 'Accepted', 'Partly Ordered', 'Ordered', 'Expired', 'Lost', 'Closed', 'Cancelled')),
    revision        INTEGER NOT NULL DEFAULT 1 CHECK (revision > 0),
    row_version     BIGINT NOT NULL DEFAULT 1,
    posted_at       TIMESTAMPTZ,
    posted_by       TEXT,
    note            TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (company_id, code),
    CHECK (valid_until IS NULL OR valid_until >= quote_date)
);

CREATE TABLE fast_erp.sales_quote_items (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quote_id        BIGINT NOT NULL REFERENCES fast_erp.sales_quotes(id) ON DELETE CASCADE,
    line_number     INTEGER NOT NULL,
    item_id         BIGINT REFERENCES fast_erp.items(id),
    warehouse_id    BIGINT REFERENCES fast_erp.warehouses(id),
    description     TEXT,
    uom_id          BIGINT REFERENCES fast_erp.uoms(id),
    qty             NUMERIC(20, 6) NOT NULL CHECK (qty > 0),
    rate            NUMERIC(20, 6) NOT NULL CHECK (rate >= 0),
    net_amount      NUMERIC(20, 4) NOT NULL CHECK (net_amount >= 0),
    tax_amount      NUMERIC(20, 4) NOT NULL DEFAULT 0 CHECK (tax_amount >= 0),
    amount          NUMERIC(20, 4) NOT NULL CHECK (amount >= 0),
    ordered_qty     NUMERIC(20, 6) NOT NULL DEFAULT 0 CHECK (ordered_qty >= 0),
    tax_code_id     BIGINT REFERENCES fast_erp.tax_codes(id),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (quote_id, line_number)
);

ALTER TABLE fast_erp.sales_orders
    ADD COLUMN IF NOT EXISTS quote_id BIGINT REFERENCES fast_erp.sales_quotes(id);
ALTER TABLE fast_erp.sales_order_items
    ADD COLUMN IF NOT EXISTS quote_item_id BIGINT REFERENCES fast_erp.sales_quote_items(id);

CREATE TABLE fast_erp.purchase_requests (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    code            TEXT NOT NULL,
    request_date    DATE NOT NULL,
    required_by     DATE,
    document_state  TEXT NOT NULL DEFAULT 'Draft'
                    CHECK (document_state IN ('Draft', 'Pending Approval', 'Approved', 'Posted', 'Closed', 'Cancelled')),
    status          TEXT NOT NULL DEFAULT 'Open'
                    CHECK (status IN ('Open', 'RFQ Created', 'Partly Ordered', 'Ordered', 'Closed', 'Cancelled')),
    requested_by    TEXT,
    note            TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (company_id, code),
    CHECK (required_by IS NULL OR required_by >= request_date)
);

CREATE TABLE fast_erp.purchase_request_items (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_request_id BIGINT NOT NULL REFERENCES fast_erp.purchase_requests(id) ON DELETE CASCADE,
    line_number     INTEGER NOT NULL,
    item_id         BIGINT NOT NULL REFERENCES fast_erp.items(id),
    warehouse_id    BIGINT REFERENCES fast_erp.warehouses(id),
    uom_id          BIGINT REFERENCES fast_erp.uoms(id),
    qty             NUMERIC(20, 6) NOT NULL CHECK (qty > 0),
    ordered_qty     NUMERIC(20, 6) NOT NULL DEFAULT 0 CHECK (ordered_qty >= 0),
    description     TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (purchase_request_id, line_number)
);

CREATE TABLE fast_erp.requests_for_quote (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    code            TEXT NOT NULL,
    request_date    DATE NOT NULL,
    response_due    DATE,
    document_state  TEXT NOT NULL DEFAULT 'Draft'
                    CHECK (document_state IN ('Draft', 'Posted', 'Closed', 'Cancelled')),
    status          TEXT NOT NULL DEFAULT 'Open'
                    CHECK (status IN ('Open', 'Responses Received', 'Awarded', 'Closed', 'Cancelled')),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (company_id, code),
    CHECK (response_due IS NULL OR response_due >= request_date)
);

CREATE TABLE fast_erp.rfq_items (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rfq_id          BIGINT NOT NULL REFERENCES fast_erp.requests_for_quote(id) ON DELETE CASCADE,
    line_number     INTEGER NOT NULL,
    purchase_request_item_id BIGINT REFERENCES fast_erp.purchase_request_items(id),
    item_id         BIGINT NOT NULL REFERENCES fast_erp.items(id),
    warehouse_id    BIGINT REFERENCES fast_erp.warehouses(id),
    uom_id          BIGINT REFERENCES fast_erp.uoms(id),
    qty             NUMERIC(20, 6) NOT NULL CHECK (qty > 0),
    description     TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (rfq_id, line_number)
);

CREATE TABLE fast_erp.rfq_suppliers (
    rfq_id          BIGINT NOT NULL REFERENCES fast_erp.requests_for_quote(id) ON DELETE CASCADE,
    supplier_id     BIGINT NOT NULL REFERENCES fast_erp.suppliers(id),
    sent_at         TIMESTAMPTZ,
    responded_at    TIMESTAMPTZ,
    PRIMARY KEY (rfq_id, supplier_id)
);

CREATE TABLE fast_erp.supplier_quotations (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    code            TEXT NOT NULL,
    rfq_id          BIGINT REFERENCES fast_erp.requests_for_quote(id),
    supplier_id     BIGINT NOT NULL REFERENCES fast_erp.suppliers(id),
    quote_date      DATE NOT NULL,
    valid_until     DATE,
    currency        CHAR(3) NOT NULL REFERENCES fast_erp.currencies(code),
    exchange_rate   NUMERIC(20, 10) NOT NULL DEFAULT 1 CHECK (exchange_rate > 0),
    total           NUMERIC(20, 4) NOT NULL DEFAULT 0 CHECK (total >= 0),
    document_state  TEXT NOT NULL DEFAULT 'Draft'
                    CHECK (document_state IN ('Draft', 'Posted', 'Closed', 'Cancelled')),
    status          TEXT NOT NULL DEFAULT 'Open'
                    CHECK (status IN ('Open', 'Accepted', 'Rejected', 'Expired', 'Ordered', 'Closed', 'Cancelled')),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (company_id, code),
    CHECK (valid_until IS NULL OR valid_until >= quote_date)
);

CREATE TABLE fast_erp.supplier_quotation_items (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_quotation_id BIGINT NOT NULL REFERENCES fast_erp.supplier_quotations(id) ON DELETE CASCADE,
    line_number     INTEGER NOT NULL,
    rfq_item_id     BIGINT REFERENCES fast_erp.rfq_items(id),
    item_id         BIGINT NOT NULL REFERENCES fast_erp.items(id),
    uom_id          BIGINT REFERENCES fast_erp.uoms(id),
    qty             NUMERIC(20, 6) NOT NULL CHECK (qty > 0),
    rate            NUMERIC(20, 6) NOT NULL CHECK (rate >= 0),
    amount          NUMERIC(20, 4) NOT NULL CHECK (amount >= 0),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (supplier_quotation_id, line_number)
);

ALTER TABLE fast_erp.purchase_orders
    ADD COLUMN IF NOT EXISTS supplier_quotation_id BIGINT REFERENCES fast_erp.supplier_quotations(id);

ALTER TABLE fast_erp.payment_allocations
    ADD COLUMN IF NOT EXISTS payment_amount NUMERIC(20, 4),
    ADD COLUMN IF NOT EXISTS invoice_amount NUMERIC(20, 4),
    ADD COLUMN IF NOT EXISTS base_amount NUMERIC(20, 4),
    ADD COLUMN IF NOT EXISTS exchange_gain_loss NUMERIC(20, 4) NOT NULL DEFAULT 0;

UPDATE fast_erp.payment_allocations
   SET payment_amount = COALESCE(payment_amount, amount),
       invoice_amount = COALESCE(invoice_amount, amount),
       base_amount = COALESCE(base_amount, amount);

ALTER TABLE fast_erp.payment_allocations
    ALTER COLUMN payment_amount SET NOT NULL,
    ALTER COLUMN invoice_amount SET NOT NULL,
    ALTER COLUMN base_amount SET NOT NULL,
    ADD CONSTRAINT payment_allocations_currency_amounts_check
        CHECK (payment_amount > 0 AND invoice_amount > 0 AND base_amount > 0);

ALTER TABLE fast_erp.supplier_payment_allocations
    ADD COLUMN IF NOT EXISTS payment_amount NUMERIC(20, 4),
    ADD COLUMN IF NOT EXISTS invoice_amount NUMERIC(20, 4),
    ADD COLUMN IF NOT EXISTS base_amount NUMERIC(20, 4),
    ADD COLUMN IF NOT EXISTS exchange_gain_loss NUMERIC(20, 4) NOT NULL DEFAULT 0;

UPDATE fast_erp.supplier_payment_allocations
   SET payment_amount = COALESCE(payment_amount, amount),
       invoice_amount = COALESCE(invoice_amount, amount),
       base_amount = COALESCE(base_amount, amount);

ALTER TABLE fast_erp.supplier_payment_allocations
    ALTER COLUMN payment_amount SET NOT NULL,
    ALTER COLUMN invoice_amount SET NOT NULL,
    ALTER COLUMN base_amount SET NOT NULL,
    ADD CONSTRAINT supplier_payment_allocations_currency_amounts_check
        CHECK (payment_amount > 0 AND invoice_amount > 0 AND base_amount > 0);

CREATE INDEX idx_sales_quotes_company_status ON fast_erp.sales_quotes (company_id, status, quote_date);
CREATE INDEX idx_purchase_requests_company_status ON fast_erp.purchase_requests (company_id, status, request_date);
CREATE INDEX idx_rfqs_company_status ON fast_erp.requests_for_quote (company_id, status, request_date);
CREATE INDEX idx_supplier_quotes_company_status ON fast_erp.supplier_quotations (company_id, status, quote_date);

INSERT INTO fast_erp.schema_migrations (version)
VALUES ('0009_preorder_and_allocation_details')
ON CONFLICT (version) DO NOTHING;
