-- Stable currency migration identity and complete posting account defaults.

ALTER TABLE fast_erp.currencies
    ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE fast_erp.currencies
    ADD CONSTRAINT currencies_id_unique UNIQUE (id);

ALTER TABLE fast_erp.company_accounting_settings
    ADD COLUMN IF NOT EXISTS goods_received_not_invoiced_account_id BIGINT REFERENCES fast_erp.accounts(id),
    ADD COLUMN IF NOT EXISTS stock_delivered_not_billed_account_id BIGINT REFERENCES fast_erp.accounts(id),
    ADD COLUMN IF NOT EXISTS customer_advance_account_id BIGINT REFERENCES fast_erp.accounts(id),
    ADD COLUMN IF NOT EXISTS supplier_advance_account_id BIGINT REFERENCES fast_erp.accounts(id),
    ADD COLUMN IF NOT EXISTS inventory_adjustment_account_id BIGINT REFERENCES fast_erp.accounts(id),
    ADD COLUMN IF NOT EXISTS rounding_gain_account_id BIGINT REFERENCES fast_erp.accounts(id),
    ADD COLUMN IF NOT EXISTS rounding_loss_account_id BIGINT REFERENCES fast_erp.accounts(id);

INSERT INTO fast_erp.schema_migrations (version)
VALUES ('0010_accounting_defaults_and_currency_identity')
ON CONFLICT (version) DO NOTHING;
