-- Physical stock identity, reservations, shelf life, and manual temperature control.

CREATE TABLE fast_erp.temperature_zones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    warehouse_id BIGINT NOT NULL REFERENCES fast_erp.warehouses(id),
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    minimum_c NUMERIC(8, 3) NOT NULL,
    maximum_c NUMERIC(8, 3) NOT NULL,
    reading_interval_hours INTEGER NOT NULL DEFAULT 24 CHECK (reading_interval_hours > 0),
    active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (company_id, warehouse_id, code),
    CHECK (minimum_c < maximum_c)
);

CREATE TABLE fast_erp.warehouse_locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    warehouse_id BIGINT NOT NULL REFERENCES fast_erp.warehouses(id),
    parent_id BIGINT REFERENCES fast_erp.warehouse_locations(id),
    temperature_zone_id BIGINT REFERENCES fast_erp.temperature_zones(id),
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    location_type TEXT NOT NULL DEFAULT 'Bin'
        CHECK (location_type IN ('Zone', 'Aisle', 'Shelf', 'Bin', 'Receiving', 'QC', 'Dispatch')),
    pickable BOOLEAN NOT NULL DEFAULT true,
    active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (company_id, warehouse_id, code),
    CHECK (parent_id IS NULL OR parent_id <> id)
);

CREATE TABLE fast_erp.stock_slices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    item_id BIGINT NOT NULL REFERENCES fast_erp.items(id),
    warehouse_id BIGINT NOT NULL REFERENCES fast_erp.warehouses(id),
    location_id BIGINT NOT NULL REFERENCES fast_erp.warehouse_locations(id),
    batch_id BIGINT REFERENCES fast_erp.batches(id),
    serial_number_id BIGINT REFERENCES fast_erp.serial_numbers(id),
    disposition TEXT NOT NULL DEFAULT 'Available'
        CHECK (disposition IN ('Available', 'QC', 'Hold', 'Rejected', 'Damaged')),
    quantity NUMERIC(20, 6) NOT NULL DEFAULT 0 CHECK (quantity >= 0),
    reserved_qty NUMERIC(20, 6) NOT NULL DEFAULT 0 CHECK (reserved_qty >= 0 AND reserved_qty <= quantity),
    first_received_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE NULLS NOT DISTINCT (company_id, item_id, warehouse_id, location_id,
                               batch_id, serial_number_id, disposition),
    CHECK (serial_number_id IS NULL OR quantity <= 1)
);
CREATE INDEX idx_wms_stock_fefo ON fast_erp.stock_slices
    (company_id, item_id, warehouse_id, disposition, batch_id)
    WHERE quantity > 0;
CREATE INDEX idx_wms_stock_location ON fast_erp.stock_slices(location_id)
    WHERE quantity > 0;

CREATE TABLE fast_erp.inventory_allocation_splits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ledger_entry_id BIGINT NOT NULL REFERENCES fast_erp.inventory_ledger_entries(id),
    company_id BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    item_id BIGINT NOT NULL REFERENCES fast_erp.items(id),
    warehouse_id BIGINT NOT NULL REFERENCES fast_erp.warehouses(id),
    location_id BIGINT NOT NULL REFERENCES fast_erp.warehouse_locations(id),
    batch_id BIGINT REFERENCES fast_erp.batches(id),
    serial_number_id BIGINT REFERENCES fast_erp.serial_numbers(id),
    disposition TEXT NOT NULL
        CHECK (disposition IN ('Available', 'QC', 'Hold', 'Rejected', 'Damaged')),
    quantity_change NUMERIC(20, 6) NOT NULL CHECK (quantity_change <> 0),
    source_split_id BIGINT REFERENCES fast_erp.inventory_allocation_splits(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (serial_number_id IS NULL OR abs(quantity_change) = 1)
);
CREATE TRIGGER inventory_allocation_splits_immutable
BEFORE UPDATE OR DELETE ON fast_erp.inventory_allocation_splits
FOR EACH ROW EXECUTE FUNCTION fast_erp.reject_immutable_ledger_mutation();
CREATE INDEX idx_wms_splits_ledger ON fast_erp.inventory_allocation_splits(ledger_entry_id);
CREATE INDEX idx_wms_splits_lot ON fast_erp.inventory_allocation_splits(company_id, batch_id, created_at);

CREATE TABLE fast_erp.warehouse_transfers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    item_id BIGINT NOT NULL REFERENCES fast_erp.items(id),
    warehouse_id BIGINT NOT NULL REFERENCES fast_erp.warehouses(id),
    from_location_id BIGINT NOT NULL REFERENCES fast_erp.warehouse_locations(id),
    to_location_id BIGINT NOT NULL REFERENCES fast_erp.warehouse_locations(id),
    batch_id BIGINT REFERENCES fast_erp.batches(id),
    serial_number_id BIGINT REFERENCES fast_erp.serial_numbers(id),
    from_disposition TEXT NOT NULL,
    to_disposition TEXT NOT NULL,
    quantity NUMERIC(20, 6) NOT NULL CHECK (quantity > 0),
    actor TEXT NOT NULL,
    reason TEXT NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (from_location_id <> to_location_id OR from_disposition <> to_disposition)
);
CREATE TRIGGER warehouse_transfers_immutable
BEFORE UPDATE OR DELETE ON fast_erp.warehouse_transfers
FOR EACH ROW EXECUTE FUNCTION fast_erp.reject_immutable_ledger_mutation();
CREATE INDEX idx_wms_transfers_lot ON fast_erp.warehouse_transfers(company_id,batch_id,occurred_at);

CREATE TABLE fast_erp.stock_reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    sales_order_item_id BIGINT NOT NULL REFERENCES fast_erp.sales_order_items(id),
    stock_slice_id BIGINT NOT NULL REFERENCES fast_erp.stock_slices(id),
    quantity NUMERIC(20, 6) NOT NULL CHECK (quantity > 0),
    consumed_qty NUMERIC(20, 6) NOT NULL DEFAULT 0
        CHECK (consumed_qty >= 0 AND consumed_qty <= quantity),
    status TEXT NOT NULL DEFAULT 'Active'
        CHECK (status IN ('Active', 'Consumed', 'Released')),
    reserved_by TEXT NOT NULL,
    reserved_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at TIMESTAMPTZ,
    released_at TIMESTAMPTZ,
    release_reason TEXT
);
CREATE INDEX idx_wms_reservations_slice ON fast_erp.stock_reservations(stock_slice_id, status);
CREATE UNIQUE INDEX idx_wms_active_order_slice
ON fast_erp.stock_reservations(sales_order_item_id, stock_slice_id)
WHERE status = 'Active';

CREATE TABLE fast_erp.lot_holds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    batch_id BIGINT NOT NULL REFERENCES fast_erp.batches(id),
    reason TEXT NOT NULL,
    created_by TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    released_by TEXT,
    released_at TIMESTAMPTZ,
    release_reason TEXT,
    CHECK ((released_at IS NULL) = (released_by IS NULL))
);
CREATE INDEX idx_wms_active_lot_holds ON fast_erp.lot_holds(company_id, batch_id)
WHERE released_at IS NULL;

CREATE TABLE fast_erp.temperature_readings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    zone_id BIGINT NOT NULL REFERENCES fast_erp.temperature_zones(id),
    measured_at TIMESTAMPTZ NOT NULL,
    temperature_c NUMERIC(8, 3) NOT NULL,
    recorded_by TEXT NOT NULL,
    note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_wms_temperature_readings ON fast_erp.temperature_readings(zone_id, measured_at DESC);

CREATE TABLE fast_erp.temperature_excursions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    zone_id BIGINT NOT NULL REFERENCES fast_erp.temperature_zones(id),
    reading_id BIGINT NOT NULL UNIQUE REFERENCES fast_erp.temperature_readings(id),
    status TEXT NOT NULL DEFAULT 'Open' CHECK (status IN ('Open', 'Released')),
    opened_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    reviewed_by TEXT,
    reviewed_at TIMESTAMPTZ,
    review_reason TEXT,
    CHECK ((status = 'Open') = (reviewed_at IS NULL))
);
CREATE INDEX idx_wms_open_excursions ON fast_erp.temperature_excursions(zone_id)
WHERE status = 'Open';

ALTER TABLE fast_erp.customers
ADD COLUMN min_remaining_shelf_life_days INTEGER NOT NULL DEFAULT 0
CHECK (min_remaining_shelf_life_days >= 0);

-- Existing physical stock cannot be assigned a verified lot or bin retroactively.
-- Carry warehouse totals into a visible opening slice; tracked goods start on hold.
INSERT INTO fast_erp.warehouse_locations(company_id, warehouse_id, code, name,
                                         location_type, pickable)
SELECT warehouse.company_id, warehouse.id, 'DEFAULT', 'Default location', 'Bin', true
FROM fast_erp.warehouses warehouse
ON CONFLICT (company_id, warehouse_id, code) DO NOTHING;

INSERT INTO fast_erp.stock_slices(company_id, item_id, warehouse_id, location_id,
                                  disposition, quantity)
SELECT balance.company_id, balance.item_id, balance.warehouse_id, location.id,
       CASE WHEN item.tracks_batches OR item.tracks_serials THEN 'Hold' ELSE 'Available' END,
       balance.quantity
FROM fast_erp.inventory_balances balance
JOIN fast_erp.items item ON item.id = balance.item_id
JOIN fast_erp.warehouse_locations location
  ON location.warehouse_id = balance.warehouse_id AND location.code = 'DEFAULT'
WHERE balance.quantity > 0
ON CONFLICT DO NOTHING;

-- AI query and dashboard surfaces. A missing tenant setting returns no rows.
CREATE VIEW fast_erp.wms_stock_report AS
SELECT slice.company_id, slice.id AS stock_slice_id,
       slice.location_id, slice.batch_id, slice.serial_number_id,
       item.code AS item_code, item.name AS item_name,
       warehouse.code AS warehouse_code, location.code AS location_code,
       batch.batch_code AS lot_code, batch.expires_on AS expiry_date,
       serial.serial_code, slice.disposition, slice.quantity AS on_hand,
       slice.reserved_qty AS reserved,
       CASE WHEN slice.disposition='Available' AND location.pickable
                 AND (NOT item.tracks_expiry OR batch.expires_on IS NOT NULL)
                 AND (batch.expires_on IS NULL OR batch.expires_on >= current_date)
                 AND NOT EXISTS (SELECT 1 FROM fast_erp.lot_holds hold
                                 WHERE hold.batch_id=slice.batch_id AND hold.released_at IS NULL)
                 AND NOT EXISTS (SELECT 1 FROM fast_erp.temperature_excursions excursion
                                 WHERE excursion.zone_id=location.temperature_zone_id
                                   AND excursion.status='Open')
            THEN slice.quantity-slice.reserved_qty ELSE 0 END AS available,
       CASE WHEN slice.disposition<>'Available' OR
                 (batch.expires_on IS NOT NULL AND batch.expires_on<current_date) OR
                 EXISTS (SELECT 1 FROM fast_erp.lot_holds hold
                         WHERE hold.batch_id=slice.batch_id AND hold.released_at IS NULL) OR
                 EXISTS (SELECT 1 FROM fast_erp.temperature_excursions excursion
                         WHERE excursion.zone_id=location.temperature_zone_id
                           AND excursion.status='Open')
            THEN slice.quantity ELSE 0 END AS held
FROM fast_erp.stock_slices slice
JOIN fast_erp.items item ON item.id=slice.item_id
JOIN fast_erp.warehouses warehouse ON warehouse.id=slice.warehouse_id
JOIN fast_erp.warehouse_locations location ON location.id=slice.location_id
LEFT JOIN fast_erp.batches batch ON batch.id=slice.batch_id
LEFT JOIN fast_erp.serial_numbers serial ON serial.id=slice.serial_number_id
WHERE slice.company_id=current_setting('fasterp.company_id',true)::bigint;

CREATE VIEW fast_erp.wms_movement_report AS
SELECT split.company_id, split.id AS movement_id, event.event_date,
       event.event_type, event.voucher_code,
       item.code AS item_code, item.name AS item_name,
       warehouse.code AS warehouse_code, location.code AS location_code,
       batch.batch_code AS lot_code, serial.serial_code,
       split.disposition, split.quantity_change
FROM fast_erp.inventory_allocation_splits split
JOIN fast_erp.inventory_ledger_entries ledger ON ledger.id=split.ledger_entry_id
JOIN fast_erp.inventory_events event ON event.id=ledger.event_id
JOIN fast_erp.items item ON item.id=split.item_id
JOIN fast_erp.warehouses warehouse ON warehouse.id=split.warehouse_id
JOIN fast_erp.warehouse_locations location ON location.id=split.location_id
LEFT JOIN fast_erp.batches batch ON batch.id=split.batch_id
LEFT JOIN fast_erp.serial_numbers serial ON serial.id=split.serial_number_id
WHERE split.company_id=current_setting('fasterp.company_id',true)::bigint
UNION ALL
SELECT transfer.company_id, -(transfer.id*2) AS movement_id,
       transfer.occurred_at::date AS event_date, 'Transfer' AS event_type,
       'WT-' || transfer.id::text AS voucher_code,
       item.code AS item_code,item.name AS item_name,
       warehouse.code AS warehouse_code,location.code AS location_code,
       batch.batch_code AS lot_code,serial.serial_code,
       transfer.from_disposition AS disposition,-transfer.quantity AS quantity_change
FROM fast_erp.warehouse_transfers transfer
JOIN fast_erp.items item ON item.id=transfer.item_id
JOIN fast_erp.warehouses warehouse ON warehouse.id=transfer.warehouse_id
JOIN fast_erp.warehouse_locations location ON location.id=transfer.from_location_id
LEFT JOIN fast_erp.batches batch ON batch.id=transfer.batch_id
LEFT JOIN fast_erp.serial_numbers serial ON serial.id=transfer.serial_number_id
WHERE transfer.company_id=current_setting('fasterp.company_id',true)::bigint
UNION ALL
SELECT transfer.company_id, -(transfer.id*2+1) AS movement_id,
       transfer.occurred_at::date AS event_date, 'Transfer' AS event_type,
       'WT-' || transfer.id::text AS voucher_code,
       item.code AS item_code,item.name AS item_name,
       warehouse.code AS warehouse_code,location.code AS location_code,
       batch.batch_code AS lot_code,serial.serial_code,
       transfer.to_disposition AS disposition,transfer.quantity AS quantity_change
FROM fast_erp.warehouse_transfers transfer
JOIN fast_erp.items item ON item.id=transfer.item_id
JOIN fast_erp.warehouses warehouse ON warehouse.id=transfer.warehouse_id
JOIN fast_erp.warehouse_locations location ON location.id=transfer.to_location_id
LEFT JOIN fast_erp.batches batch ON batch.id=transfer.batch_id
LEFT JOIN fast_erp.serial_numbers serial ON serial.id=transfer.serial_number_id
WHERE transfer.company_id=current_setting('fasterp.company_id',true)::bigint;

CREATE VIEW fast_erp.wms_lot_report AS
SELECT batch.company_id, batch.id AS batch_id, item.code AS item_code,
       item.name AS item_name, batch.batch_code AS lot_code,
       batch.manufactured_on, batch.expires_on AS expiry_date,
       COALESCE(sum(slice.quantity),0) AS on_hand,
       COALESCE(sum(slice.reserved_qty),0) AS reserved,
       EXISTS (SELECT 1 FROM fast_erp.lot_holds hold WHERE hold.batch_id=batch.id
               AND hold.released_at IS NULL) AS on_hold
FROM fast_erp.batches batch
JOIN fast_erp.items item ON item.id=batch.item_id
LEFT JOIN fast_erp.stock_slices slice ON slice.batch_id=batch.id
WHERE batch.company_id=current_setting('fasterp.company_id',true)::bigint
GROUP BY batch.company_id,batch.id,item.code,item.name,batch.batch_code,
         batch.manufactured_on,batch.expires_on;

CREATE VIEW fast_erp.wms_temperature_report AS
SELECT reading.company_id, reading.id AS reading_id, zone.code AS zone_code,
       warehouse.code AS warehouse_code, reading.measured_at,
       reading.temperature_c, zone.minimum_c, zone.maximum_c,
       reading.recorded_by,
       CASE WHEN excursion.status='Open' THEN true ELSE false END AS open_excursion
FROM fast_erp.temperature_readings reading
JOIN fast_erp.temperature_zones zone ON zone.id=reading.zone_id
JOIN fast_erp.warehouses warehouse ON warehouse.id=zone.warehouse_id
LEFT JOIN fast_erp.temperature_excursions excursion ON excursion.reading_id=reading.id
WHERE reading.company_id=current_setting('fasterp.company_id',true)::bigint;

INSERT INTO fast_erp.schema_migrations(version)
VALUES ('0014_warehouse_inventory')
ON CONFLICT (version) DO NOTHING;
