-- Audited cycle counts and inventory adjustments.

CREATE TABLE fast_erp.warehouse_stock_counts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    stock_slice_id BIGINT NOT NULL REFERENCES fast_erp.stock_slices(id),
    item_id BIGINT NOT NULL REFERENCES fast_erp.items(id),
    warehouse_id BIGINT NOT NULL REFERENCES fast_erp.warehouses(id),
    location_id BIGINT NOT NULL REFERENCES fast_erp.warehouse_locations(id),
    batch_id BIGINT REFERENCES fast_erp.batches(id),
    serial_number_id BIGINT REFERENCES fast_erp.serial_numbers(id),
    disposition TEXT NOT NULL,
    expected_qty NUMERIC(20, 6) NOT NULL CHECK (expected_qty >= 0),
    counted_qty NUMERIC(20, 6) NOT NULL CHECK (counted_qty >= 0),
    variance_qty NUMERIC(20, 6) NOT NULL,
    adjustment_account_id BIGINT REFERENCES fast_erp.accounts(id),
    inventory_event_id BIGINT REFERENCES fast_erp.inventory_events(id),
    posting_batch_id BIGINT REFERENCES fast_erp.posting_batches(id),
    counted_by TEXT NOT NULL,
    reason TEXT NOT NULL,
    counted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (variance_qty = counted_qty - expected_qty)
);
CREATE TRIGGER warehouse_stock_counts_immutable
BEFORE UPDATE OR DELETE ON fast_erp.warehouse_stock_counts
FOR EACH ROW EXECUTE FUNCTION fast_erp.reject_immutable_ledger_mutation();
CREATE INDEX idx_wms_counts_slice ON fast_erp.warehouse_stock_counts
    (company_id, stock_slice_id, counted_at DESC);

CREATE TABLE fast_erp.warehouse_interwarehouse_transfers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    item_id BIGINT NOT NULL REFERENCES fast_erp.items(id),
    from_warehouse_id BIGINT NOT NULL REFERENCES fast_erp.warehouses(id),
    to_warehouse_id BIGINT NOT NULL REFERENCES fast_erp.warehouses(id),
    from_location_id BIGINT NOT NULL REFERENCES fast_erp.warehouse_locations(id),
    to_location_id BIGINT NOT NULL REFERENCES fast_erp.warehouse_locations(id),
    batch_id BIGINT REFERENCES fast_erp.batches(id),
    serial_number_id BIGINT REFERENCES fast_erp.serial_numbers(id),
    disposition TEXT NOT NULL,
    quantity NUMERIC(20, 6) NOT NULL CHECK (quantity > 0),
    outbound_event_id BIGINT NOT NULL REFERENCES fast_erp.inventory_events(id),
    inbound_event_id BIGINT NOT NULL REFERENCES fast_erp.inventory_events(id),
    actor TEXT NOT NULL,
    reason TEXT NOT NULL,
    transferred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (from_warehouse_id <> to_warehouse_id)
);
CREATE TRIGGER warehouse_interwarehouse_transfers_immutable
BEFORE UPDATE OR DELETE ON fast_erp.warehouse_interwarehouse_transfers
FOR EACH ROW EXECUTE FUNCTION fast_erp.reject_immutable_ledger_mutation();
CREATE INDEX idx_wms_interwarehouse_lot ON fast_erp.warehouse_interwarehouse_transfers
    (company_id, batch_id, transferred_at DESC);

CREATE TABLE fast_erp.warehouse_opening_imports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    offset_account_id BIGINT NOT NULL REFERENCES fast_erp.accounts(id),
    inventory_event_id BIGINT NOT NULL REFERENCES fast_erp.inventory_events(id),
    posting_batch_id BIGINT REFERENCES fast_erp.posting_batches(id),
    payload_hash TEXT NOT NULL,
    row_count INTEGER NOT NULL CHECK (row_count > 0),
    imported_by TEXT NOT NULL,
    reason TEXT NOT NULL,
    imported_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (company_id, payload_hash)
);
CREATE TRIGGER warehouse_opening_imports_immutable
BEFORE UPDATE OR DELETE ON fast_erp.warehouse_opening_imports
FOR EACH ROW EXECUTE FUNCTION fast_erp.reject_immutable_ledger_mutation();

CREATE TABLE fast_erp.warehouse_stock_identifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    item_id BIGINT NOT NULL REFERENCES fast_erp.items(id),
    warehouse_id BIGINT NOT NULL REFERENCES fast_erp.warehouses(id),
    source_stock_slice_id BIGINT NOT NULL REFERENCES fast_erp.stock_slices(id),
    destination_location_id BIGINT NOT NULL REFERENCES fast_erp.warehouse_locations(id),
    batch_id BIGINT REFERENCES fast_erp.batches(id),
    serial_number_id BIGINT REFERENCES fast_erp.serial_numbers(id),
    quantity NUMERIC(20, 6) NOT NULL CHECK (quantity > 0),
    identified_by TEXT NOT NULL,
    reason TEXT NOT NULL,
    identified_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TRIGGER warehouse_stock_identifications_immutable
BEFORE UPDATE OR DELETE ON fast_erp.warehouse_stock_identifications
FOR EACH ROW EXECUTE FUNCTION fast_erp.reject_immutable_ledger_mutation();
CREATE INDEX idx_wms_identifications_lot ON fast_erp.warehouse_stock_identifications
    (company_id, batch_id, identified_at DESC);

INSERT INTO fast_erp.schema_migrations(version)
VALUES ('0015_warehouse_counts')
ON CONFLICT (version) DO NOTHING;
