-- Audited lot date corrections and one physical position per serial.

CREATE UNIQUE INDEX idx_wms_one_positive_serial_position
ON fast_erp.stock_slices(company_id, serial_number_id)
WHERE serial_number_id IS NOT NULL AND quantity > 0;

CREATE TABLE fast_erp.warehouse_lot_amendments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES fast_erp.companies(id),
    batch_id BIGINT NOT NULL REFERENCES fast_erp.batches(id),
    old_manufactured_on DATE,
    new_manufactured_on DATE,
    old_expires_on DATE,
    new_expires_on DATE,
    amended_by TEXT NOT NULL,
    reason TEXT NOT NULL,
    amended_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (old_manufactured_on IS DISTINCT FROM new_manufactured_on OR
           old_expires_on IS DISTINCT FROM new_expires_on)
);
CREATE TRIGGER warehouse_lot_amendments_immutable
BEFORE UPDATE OR DELETE ON fast_erp.warehouse_lot_amendments
FOR EACH ROW EXECUTE FUNCTION fast_erp.reject_immutable_ledger_mutation();
CREATE INDEX idx_wms_lot_amendments_lot ON fast_erp.warehouse_lot_amendments
    (company_id,batch_id,amended_at DESC);

INSERT INTO fast_erp.schema_migrations(version)
VALUES ('0017_lot_amendments')
ON CONFLICT (version) DO NOTHING;
